### ISSUE TITLE
No falaise programs running due to libicudata version

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#102]
flsimulate, flreconstruct crash with this error. It's not wrong - since doing a brew upgrade the other day (to try and fix something else... it is not my week...), I have v61 of this library. Do you know how I can get it to look for the right one?

```
dyld: Library not loaded: /Users/cpatrick/CadfaelBrew/opt/icu4c/lib/libicudata.60.2.dylib
  Referenced from: /Users/cpatrick/CadfaelBrew/opt/boost/lib/libboost_regex-mt.dylib
  Reason: image not found
Abort trap: 6
```

Sorry for this, everything is going wrong this week.

**Comment by drbenmorgan** [comment]
@cherylepatrick, should be fixed by a revision bump in icu4c dependents. Try

```
$ brew update
$ brew upgrade falaise
```

You should see boost, Bayeux and Falaise rebuild/install...

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - boost is updating now so hopefully it will go well.

**Comment by cherylepatrick** [comment]
Fixed! Thanks @drbenmorgan !
