### ISSUE TITLE
Qt5-base install error 

### ISSUE THREAD

**Issue by wausain** [SuperNEMO-DBD/Falaise#109]
I'm finding issues installing falaise, specifically qt5-base with _brew install falaise_ .
Running macOS High Sierra version 10.13.5

I'm getting a huge error when attempting to install the qt5-base dependency. The end of the error is: 

**_wcontainer_mac.o  -F/private/tmp/qt5-base-20180613-17557-11pii30/qtbase-everywhere-src-5.10.0/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework AppKit -lz -framework OpenGL -framework AGL 
mv -f QtWidgets ../../lib/QtWidgets.framework/Versions/5/QtWidgets
ln -s Versions/Current/QtWidgets ../../lib/QtWidgets.framework/QtWidgets
make: *** [sub-src-make_first] Error 2_**

brew config shows: 

_**HOMEBREW_VERSION: 1.6.8-19-ge39b6f5
ORIGIN: https://github.com/Homebrew/brew
HEAD: e39b6f5891f2aa98fa2bef7775aecf73fc246afb
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6694782ab38ae1e29ad391cda890018c3f6f2e15
Core tap last commit: 65 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LINKAGE_CACHE: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.5-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: 9.4
XQuartz: N/A**_

I've installed Homebrew separately but i uninstalled Homebrew and reinstalled using cadfaelbrew and received the same error. 

I've tried brew update and brew doctor just shows:

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

_**Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/hamzah/anaconda3/bin/icu-config
  /Users/hamzah/anaconda3/bin/freetype-config
  /Users/hamzah/anaconda3/bin/xslt-config
  /Users/hamzah/anaconda3/bin/libpng16-config
  /Users/hamzah/anaconda3/bin/python3.6m-config
  /Users/hamzah/anaconda3/bin/libpng-config
  /Users/hamzah/anaconda3/bin/xml2-config
  /Users/hamzah/anaconda3/bin/python3-config
  /Users/hamzah/anaconda3/bin/curl-config
  /Users/hamzah/anaconda3/bin/ncursesw6-config
  /Users/hamzah/anaconda3/bin/pcre-config
  /Users/hamzah/anaconda3/bin/python3.6-config**_

but i've tried changing the PATH and still the same error.

I tried this before this weeks update and i got the same error then.

If you want any more output (i.e. the full error let me know)

Cheers
Hamzah

**Comment by drbenmorgan** [comment]
@wausain repost this on [supernemo-dbd/homebrew-cadfael](https://github.com/SuperNEMO-DBD/homebrew-cadfael) and follow the instructions the new issue template provides please.
