### ISSUE TITLE
flsimulate-configure bug with falaise 3.3.0

### ISSUE THREAD

**Issue by emchauve** [SuperNEMO-DBD/Falaise#111]
using latest release of falaise (3.3.0, when selecting primary event "flat_versatile_generator" or "tweakable_generator" with the Qt interface flsimulate-configure, the associated variant options keep staying disabled:

![flat_versatile](https://user-images.githubusercontent.com/28624059/42222910-b94182b6-7ed6-11e8-9979-21111ae5fe68.png)

**Comment by drbenmorgan** [comment]
Assigning to @lemiere and @fmauger . This looks like it may be related to the changes between the PR that introduced the feature, #75, and updates in 3.3.0, #101, #104 and #105. One of those has likely overidden the config somewhere.
