### ISSUE TITLE
Support reading ROOT files from xrootd

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/Falaise#117]
As reported by @emchauve in SuperNEMO-DBD/homebrew-cadfael#51, ROOT files can be read directly in the interpreter using an xrootd URL, but `flreconstruct` cannot.

I suspect this is down to this line:

https://github.com/SuperNEMO-DBD/Bayeux/blob/8e9f2b638fd52c6c65c7cee5b4bd890c78071124/source/bxbrio/src/reader.cc#L194

in Bayeux. That, IUC, tries opening on the local filesystem. The generic way to do this AFAIK is to use the File static method:

```c++
_file = TFile::Open(_filename.c_str(), mode.c_str());
```

which should delegate to the appropriate TFile implementation for the input URL.

@emchauve, if you're installing Bayeux manually, then I'd suggest just patching the line in question manually, then rebuilding/reinstall Bayeux, and try again. Otherwise let me know and I'll add a temporary patch in the Bayeux formula. 

This is just to ensure we get the right fix, once we've confirmed the issue we can submit a PR to the main Bayeux repo.

**Comment by emchauve** [comment]
I patched it yesterday, it fixed the reader within Bayeux indeed, but not for `flreconstruct`. I suspect that it is trying to read some argument through the file path `root://ccxroot.in2p3.fr:1999//hpss/in2p3.fr/...`

**Comment by drbenmorgan** [comment]
That makes sense, so at least easy to see if it passes the correct URL to `TFile::Open`. I've added @fmauger as he'll know better what preprocessing is done the URL.

**Comment by emchauve** [comment]
It looks to be related on failure to read metadata

**Comment by drbenmorgan** [comment]
How did you generate the test file from `flsimulate`? Did you use defaults, or store the metadata in a separate file?

Are you able to copy the file locally (`xrdcp`?) and run?

**Comment by emchauve** [comment]
I used defaults setting. Here is my working directory with variants and configuration file:
/sps/nemo/scratch/chauveau/software/test

Yes, the file can be retrieve with xrdcp, and flreconstruct is reading well the local copy.

**Comment by drbenmorgan** [comment]
I think you'll have to dig into the `brio_reader` to check that it's getting/passing the full `root:` URL needed. I suspect from the error that it probably is, and if so there's going to be something in the way it accesses the metadata that isn't compatible with xrootd...

**Comment by drbenmorgan** [comment]
Currently blocked by https://github.com/BxCppDev/Bayeux/issues/26

@emchauve, I'd chase this up with the Bayeux devs as it's been a while since updates and we're going to need this fairly soon for work at CC-IN2P3

**Comment by emchauve** [comment]
i found finally all the issue(s)!!!

there was first the opening "new TFile" to change into "TFile::Open" => done in develop

source/bxdpp/src/simple_data_source.cc and source/bxdpp/src/simple_brio_data_source.cc is handling case where data file path start with "file://", "https://", "ftp://", etc but not "root://"

in addition, we have to skip the check "boost::filesystem::exists(_filename)" in case of XROOTD as we can not probe existence of this file in the usual way

i will prepare a pull request for bayeux

**Comment by drbenmorgan** [comment]
Should be fixed in Falaise 4/Bayeux 3.4, please reopen if not.
