### ISSUE TITLE
falaise installation does not like my root version 6.14

### ISSUE THREAD

**Issue by HanFangXie** [SuperNEMO-DBD/Falaise#123]
I am running MacOS Mojave 10.14.  Recently I noticed that my flreconstruction failed (flsimulation and flvisualise still fine). Same error as Hamzah's repotr:  #110   My reconstruction configuration file was the same as Hamzah's official_config_nohelix.conf.
I followed the homebrew #56 to install everything again. I passed all the installation but still failed flreconstruction on the same error.  
I brew upgrad my root from 6.12 to 6.14. 
Then I tried to reinstall falaise but failed. Falaise doesnot like the new root. 

The following configuration files were considered but not accepted:

    /Users/fang/brew/share/root/cmake/ROOTConfig.cmake, version: 6.14.06
    /Users/fang/brew/Cellar/root/6.14.06/share/root/cmake/ROOTConfig.cmake, version: 6.14.06

**Comment by drbenmorgan** [comment]
Sorry, I'm not clear on exactly what's going on here. It sounds like everything up to, but not including, Falaise has been installed? ROOT has been upgraded to 6.14.06, and then `brew install falaise` attempted?

**Comment by HanFangXie** [comment]
Sorry.
Recently I found my flreconstruction failed after I upgrade my MacOS to 10.14 Mojave. Then I followed #56 to instll everything again. And brew upgrade root from 6.12 to 6.14. But flreconstruction failed again for the same reason. 
So I tried to build falaise myself rather than using brew, and during this installation, it shows falaise does not like root 6.14.

**Comment by drbenmorgan** [comment]
Thanks! Did you upgrade root *after* installing everything, but before trying to build falaise?

If so, the error is *probably* coming from Bayeux's use of root. You can try `brew reinstall bayeux` in that case, but will likely ignore the upgraded root because that's from `homebrew/core`. See what happens though.

**Comment by HanFangXie** [comment]
”error is probably coming from Bayeux's use of root“ I agree!
Yes, I "upgrade root after installing everything, but before trying to build falaise". 
Thanks, Ben, I will try brew reinstall bayeux and let you know.

**Comment by HanFangXie** [comment]
I tried brew reinstall bayeux.  

==> Reinstalling supernemo-dbd/cadfael/bayeux 
==> Installing dependencies for supernemo-dbd/cadfael/bayeux: supernemo-dbd/cadfael/root6
==> Installing supernemo-dbd/cadfael/bayeux dependency: supernemo-dbd/cadfael/root6
Error: Cannot install supernemo-dbd/cadfael/root6 because conflicting formulae are installed.
  root: because SuperNEMO requires custom root build

Please `brew unlink root` before continuing.

root here means root new version 6.14 and root6 is the old version 6.12.

**Comment by drbenmorgan** [comment]
O.k., that's sort of expected... I've updated the tap version of root to allow an install of 6.14.06. To do this you'll need to do:

``` console
$ brew rm root
$ brew update
$ brew install root6 --devel
... check here that it does install 6.14.06!
$ brew reinstall bayeux
```

Building Falaise against the new root+bayeux should then work...

**Comment by HanFangXie** [comment]
Thank Ben, that helps.
