### ISSUE TITLE
Add realistic Bi207 source calibration geometry 

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/Falaise#140]
Dear all,

Up to now, only 24 Bi207 are defined into the SuperNEMO simulation instead of 42 sources into the real detector. 
We need to add the realistic Bi207 source calibration geometry in Falaise to help for the 
demonstrator calibration.

Inputs are available in Miroslav Macko dissertation (NemoDocDB-doc-4816-v1)
page 77 Table 3.7 : Final distribution of calibration sources into 42 positions
Based on the 3D laser measurement : 
* Track path position 
Track 1 -- Track 2 = 837 mm
Track 2 -- Track 3 = 834 mm
Track 3 -- Track 4 = 839 mm
Track 4 -- Track 5 = 835 mm
Track 5 -- Track 6 = 837 mm 

* Source relative position 
source 1 -- source 2 = 427 mm
source 2 -- source 3 = 426 mm
source 3 -- source 4 = 424 mm
source 4 -- source 5 = 426 mm
source 5 -- source 6 = 425 mm 
source 6 -- source 7 = 425 mm

page 70 scheme about the relative Bi207 spot into the source frame
Page 196 Table A.3 and Table A.4 : relative source position summary
page  197 Table A-5 to A.9 : relative (to source #84) source activities 

Please add inputs if needed.
Best

**Comment by drbenmorgan** [comment]
Assignments are provisional, but implementation must have a clear responsible who's going to do the coding and testing/validation on it.

**Comment by pfranchini** [comment]
Hi @lemiere, just for my orientation in the code, the current version of the calibration source is in this part?
`resources/snemo/demonstrator/geometry/GeometryModels/source_module/source_calibration.geom`

**Comment by lemiere** [comment]
Sorry Paolo since the new falaise refactoring... I'm not able to let you know any technical details... Let see with @drbenmorgan

**Comment by drbenmorgan** [comment]
Hi @pfranchini, yes, that should be the location. The only major change in the overall resource structure is the flattening out of the extraneous "config" directory, plus the "tag" layers (the various "vX.Y.Z" directories you'll see in v3.3.0).

I'd guess that adding the realistic sources will be an addition to the existing geometry rather than a fundamental change? If so, the current structure will suffice. Otherwise, we'll need to reintroduce tags via GitCondDB. I've got a demo of this based on your previous work which now works for resource files (see drbenmorgan/GitResourceDB). However, to get this to work properly will need some refactoring in Bayeux to remove/bypass the global `datatools::fetch_path_with_env` function, plus the assumption that every file will come from an existing path on the filesystem.

**Comment by pfranchini** [comment]
Thanks @drbenmorgan also for the DB demonstrator.
Right now I am just playing with the current geometry (to familiarize myself with the coordinate system) and as you said my changes will be an update of the existing one.

**Comment by pfranchini** [comment]
Hi @lemiere, please let me summarize what I have got
- detailed description of each source (M. Macko thesis)
  - envelope orientation and framing model 
  - position of the droplet (aka "spot" in Falaise) wrt the frame (resolution ~10 um)
  - activities
- relative position of each of the 42 sources (3D laser measurements in this issue) (res.~1 mm)

Assuming the fully deployed 4th source is in the exact vertical centre (Z=0) and rescaling the relative positions can easily pass from the current geometry
![calibration_401](https://user-images.githubusercontent.com/36303180/69256740-d8a48900-0bb1-11ea-894e-6ace5d1b247a.png)
to a 42-sources one:
![calibration_fix](https://user-images.githubusercontent.com/36303180/69256739-d8a48900-0bb1-11ea-8e25-aa768bba3af2.png)

However, I do not know where the calibration sources are in the demonstrator apart from "lying in the gaps between the source foils" (`resources/snemo/demonstrator/geometry/GeometryModels/source_module/source_module.geom`). Without knowing this would not make much sense implementing differences of the order of _mm_ for each different element.
Do you have other details about the relative position of the calibration tracks and the demonstrator?

**Comment by lemiere** [comment]
Hi Paolo, 

"do not know where the calibration sources are in the demonstrator "
Since a long time, there is 6 tracks at a known position.
The source tracks are at the same position than the expected one currently in the geometry (y axis)
On the x axis, that's at 0.
About the z-axis, Carla proposed to Texas team to install 7 sources per track instead of 4 sources.
Cf   NemoDocDB-doc-4683-v3
I would like to say that the 4th source is at the middle position (0 on the z-axis) but to be sure, contact Ramon Salazar


![bi207_study](https://user-images.githubusercontent.com/20680400/69677096-71e80980-10a2-11ea-8bcb-a08632a4d855.png)

**Comment by pfranchini** [comment]
Hi @lemiere so I think the simulation I have posted before is not far from reality.
Apparently Carla's geometry never made to Falaise so will do my own thing and push it later. Will ask Ramon about but in case do you have the full 3D survey of each of the 42 sources or at that time only 7 in one raw were deployed?

**Comment by lemiere** [comment]
Hi Paolo,

That exist into a non-official version of Falaise out from a version system control... :-(
3D data is available at CCLYON. See DocDB#4954

**Comment by pfranchini** [comment]
Hi @lemiere, checking the survey I have slightly different distances from each string of sources. How did you get your distances? Have you been averaging them?

What has been surveyed by the laser? The envelope of the source?

In Y they are quite well aligned, not so much in X (is there not a weight keeping them straight once deployed?).

Do you know how to rescale the survey coordinates to the Falaise geometry? Is there a monument that give us the origin?
![position1](https://user-images.githubusercontent.com/36303180/70140623-0f3bd280-168d-11ea-8d6f-1cd80e1d5914.png)
![position2](https://user-images.githubusercontent.com/36303180/70140624-0f3bd280-168d-11ea-8661-b0738c8dfd7e.png)

**Comment by pfranchini** [comment]
Yves by email:
> I remembered a Mareck/Ramon  talk about the ADS.
> They replaced the NEMO-3 source geometry by the one showed in the attached document.

[Bismuth Sources Positions and Activities-2.pdf](https://github.com/SuperNEMO-DBD/Falaise/files/4058974/Bismuth.Sources.Positions.and.Activities-2.pdf)

I will change according to slide 2 the definition of the `source_calibration_envelope.model` and `source_calibration_carrier_frame.model`. Will still be rectangular, though.
I will assume the size of the hole 13mm x 8mm in the _carrier_ has the same size of the _envelope_ itself.

**Comment by pfranchini** [comment]
Hi @lemiere I think is done, back to you to review the geometry once again (for your convenience here https://github.com/SuperNEMO-DBD/Falaise/pull/169/commits/23c37dfa273c1edce5a611eaabbf9e1ce67ae0c0). Thanks.

**Comment by pfranchini** [comment]
More in https://github.com/pfranchini/Falaise/commit/5e848c567103aabf7e759833c745dcb2da857f02 back to @lemiere review
