### ISSUE TITLE
Flreconstruct doesn't work with Falaise2 files (Falaise3)

### ISSUE THREAD

**Issue by noeroy** [SuperNEMO-DBD/Falaise#15]
Hello,
I can't use flreconstruct to reconstruct or to create a  `.root` file from the files simulated with Falaise 2. 
Here the error I get : 
```
[noeroy@pc179 ~]$ flreconstruct -i BRIO/test_1000_0nubb.brio -o test_1000_0nubbfl3.root
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170515-27376-1qs7r7s/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170515-27376-1qs7r7s/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TArrayCMod read from file BRIO/test_1000_0nubb.brio
   has the same version (=1) as the active class but a different checksum.
   You should update the version to ClassDef(TArrayCMod,2).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   char* fArray; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   int fCapacity; //
terminate called after throwing an instance of 'std::logic_error'
  what():  [void FLReconstruct::do_postprocess(FLReconstruct::FLReconstructParams&):445: Missing services configuration file!]
Aborted
```

**Comment by noeroy** [comment]
If that can help, I found a way to do it, with the standard pipeline : 
`flreconstruct -i BRIO/test_1000_0nubb.brio -p @falaise:config/snemo/demonstrator/reconstruction/pipeline/1.0.0/flreconstruct.conf -o test_1000_0nubbfl3.root`
That works, and I can do the same to create a `.brio` file that I can reconstruct with any other pipeline. But it's the only pipeline I can use on Falaise 2 files.

**Comment by drbenmorgan** [comment]
I'd suspect this is an issue with the change in scripting/metadata API, but @fmauger can provide a better review.

**Comment by lemiere** [comment]
I installed from scratch from Cadafael to Falaise using brew on my laptop (ubuntu 16.04) and CCLyon (SL6)
I execute flsimulate and obtained that : 
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /sps/nemo/scratch/nemoprod/_var/bayeux-20170531-117802-13u2qj9/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /sps/nemo/scratch/nemoprod/_var/bayeux-20170531-117802-13u2qj9/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
That DOES NOT crashed but ....
Any idea...?

**Comment by drbenmorgan** [comment]
@lemiere This is related to Issue #5 (that was fixed in PR #12) - it is due Root's dictionary generation mechanism not stripping out absolute paths to headers. It appears to be a benign issue, at least so far there are no reported issues with reading or writing Brio files (interactive ROOT might be a different matter, but since Brio files aren't interactive, that may not matter).

It ultimately needs a fix in Bayeux - the same strategy as in #12 could be employed.

**Comment by noeroy** [comment]
I can confirm that I have this warning message on every reconstruction, not only those from Falaise2 files and that it doesn't seems to be a problem in the other cases.

**Comment by drbenmorgan** [comment]
Closing in favour of migration to full ROOT file format in Impressionist.
