### ISSUE TITLE
Task: New C++ Types for Reconstruction/Analysis

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/Falaise#155]
This is a placeholder to remind me ( but cc: @emchauve, @cherylepatrick, @yramachers, @pfranchini for info and any feedback!) on adding new C++ classes to support reconstruction and analysis. It's motivated by #142, #153 and #154 which identified several places in the code that would benefit from new C++ classes model detector/reconstruction features. These would enable cleaner and clearer code, so easier to write and maintain:

1. There are several ways electric charge is represented in code, the worst being in `particle_track_data`:

   https://github.com/SuperNEMO-DBD/Falaise/blob/26d6fd5d14796a1f721798dcea8b9920a31cdc71/source/falaise/snemo/datamodels/particle_track.h#L37-L48

   This is just dumb (what's an "undefined" or "invalid" charge?), plus is open to errors due to the implicit conversions, so test replacement with a proper scoped `enum`:

   ```c++
   enum class electric_charge_t {
     negative = -1;
     neutral = 0;
     positive = 1;
   }; 
   ```

   See [this Stackoverflow post](https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum) for the rationale/why.

2. Tracking geiger/calorimeter cell grid coordinates is via `geomtools::geom_id` (o.k. as a unique id in combo with the various "locators"), however, many interfaces use plain integers to represent tracker side/row/column etc. That's bad because these indices are strictly bounded, leading to a *ton* of error checking crud, e.g.

   https://github.com/SuperNEMO-DBD/Falaise/blob/26d6fd5d14796a1f721798dcea8b9920a31cdc71/source/falaise/snemo/geometry/gg_locator.cc#L121-L131 

   The fix will be to implement "strong types" that handle these bounds constraints for us, e.g, in pseudocode

   ```c++
   // There are only nine layers...
   class TrackerLayer {
     explicit TrackerLayer(uint32_t s) ... {
        if (s > 8) throw std::out_of_range();
      } 
     .... 
   };
   ```

   This removes all the boilerplate, and also disallows implicit conversions:

   ```c++
   double gg_locator::getXCoordOfLayer(TrackerSide side, TrackerLayer layer) const {
      return cellX_[side()][layer()];
   }
   ```

   See the [ISO CPP Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-ctor) and [this article on strong types](https://www.fluentcpp.com/2016/12/08/strong-types-for-strong-interfaces/) for the rationale/why. 

   The other main use case for this will be other bounded quantities, e.g. strict positive numbers.

3. Several cases where enums are used implicitly as integers to provide flags/bitfields, e.g (our old friend charge..):

   https://github.com/SuperNEMO-DBD/Falaise/blob/26d6fd5d14796a1f721798dcea8b9920a31cdc71/source/falaise/snemo/processing/base_gamma_builder.cc#L225-L227

   Can be solved with enum classes and modern C++, see [this article for example](https://www.justsoftwaresolutions.co.uk/cplusplus/using-enum-classes-as-bitfields.html). Also see [magic enum](https://github.com/Neargye/magic_enum).

   There are also a few places where the above is used *and* conversion to/from strings

4. A *huge* number of lines of code are devoted to implementations of the `tree_dump` member function that many classes inherit from `datatools::i_tree_dumpable`. Many of these can be removed by removing the unnecessary inheritance, but some will need retaining. The remaining complexity comes from repeated boilerplate (in several dialects), awkward split loops (`for (I = 1...N-1) {doSometing(i)}; doSomething(N)`) `and::the::usual::ultra::long::range:typenames::that::are::not:clearly::named::anyway`.

   Implement some helper functions/objects to one-line most of these operations, e.g

   ```c++
   void tree_dump(std::ostream& os, indent...) {
      tree_dump_helper x{os, indent}.
      x.tree_dump("foo", someFoo)
       .tree_dump("col", someCol.begin(), someCol.end());
   }
   ```

5. Anything else as I discover them.

Will cross reference back to related PRs.

**Comment by cherylepatrick** [comment]
I like your suggestion. And if the "charged" tracks mostly are alphas, the "2" will even be numerically right (not that that needs to matter).

**Comment by drbenmorgan** [comment]
One other thing whilst I think about it - we often store a measurement and its error as two separate doubles. Would a "Measurement" class be of use? It would, I *think* only work for symmetric Gaussian errors, but would at least keep the values together.
