### ISSUE TITLE
Review FLSimulate step hit processor configuration for "__visu.track" hits and "source" volume.

### ISSUE THREAD

**Issue by fmauger** [SuperNEMO-DBD/Falaise#16]
File "resources/config/snemo/demonstrator/simulation/geant4_control/2.1/hit_processing/step_hit_processors-only_visu_tracks.conf" contains the definition of MC hits post-processor dedicated to the production of "visu" hits. The "source.visu.hit_processor" seems to be malformed concerning the logical volumes
to be attached to it.
Current list is:
<pre>
geometry.volumes   : string[4] = \
  "source_internal_strip.model.log" \
  "source_external_strip.model.log" \
  "source_internal_support_strip.model.log" \
  "source_external_support_strip.model.log"
</pre>
but is seems to be related to a previous layout of the geometry (not 4.0).
It will be better to define this processor from volumes with specific material:
<pre>
geometry.volumes.with_materials : string[1] = "bb_source_material.basic"
</pre>

**Comment by fmauger** [comment]
Additional comment: the current geometry defines source pads in file: "resources/config/snemo/demonstrator/geometry/4.0/models/source_module/basic/source_pads.geom"
this is the place where ideal version of *pads* logical volumes are setup for SN geometry 4.0.

**Comment by drbenmorgan** [comment]
PR£ 23 merged, so closing issue
