### ISSUE TITLE
genbb/tweakable_generator

### ISSUE THREAD

**Issue by yramachers** [SuperNEMO-DBD/Falaise#167]
inconsistent keywords for tweakable_generator, between definition and ConfigurableSources.conf

Suggestion: edit ConfigurableSources.conf, line 46 - change string datafile to file

since 'file' is the expected keyword for the variant 

generator/if_tweakable/energy_mode/if_spectrum/

**Comment by drbenmorgan** [comment]
Hi @yramachers, I've patched this locally on the Warwick install, can you try that again and see if you're suggested fix works?

Let me know, and I'll add the patch here.

**Comment by yramachers** [comment]
Yes, in principle, the event generator is being set up or at least recognized correctly but the this happens at the end of the Geant4 init output when starting the simulation:

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : InvalidArgument
      issued by : mctools::g4::primary_generator::_generate_event
Particle named 'gamma' has no valid kinetic energy provided by the event generator !
*** Run Must Be Aborted ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

Looks like the event generator wasn't actually set up correctly. No earlier output suggests anything wrong up to that point. This needs more investigation.

**Comment by drbenmorgan** [comment]
What datafile did you use as input for the spectrum? I can't spot any obvious issue in the config files other than the `datafile` issue. Possible issues include

- Format/content of the datafile itself (ultimately ends up in, and thus compatible with, `genbb`'s `single_particle_generator`, through the parameters `spectrum.mode` and `spectrum.data_file`
- Parameter consistency. There are three places the tweakable generator is defined/used:
  - resources/genbb/ConfigurableSources.conf
  - resources/genbb/GenBB.csv
  - resources/genbb/variants/peg.conf

**Comment by yramachers** [comment]
Ok, I think I resolved it. I used the example in Bayeux at the end of the single_particle... code as an example for an input file for histogram data. That example is slightly wrong unfortunately which only becomes clear when reading the source code.

The initial special line in such an input file is given as #@limits nbins, min, max and then as a second special line the #@energy_unit keV, after which the actual data follow line by line.

However, the initial two special lines need to be in reverse order, energy_unit keyword first, then limits keyword. The source code sets a default energy unit of MeV. If the limiting energies, min and max are set first then they have MeV units before the unit is changed to keV, i.e. generating a kinetic energy random number is unlikely or impossible. If the energy unit is set first then no confusion can arise.

After swapping the two lines in the input file, the simulation proceeds without an error. That should have resolved the issue. 

The example text file pasted below is the measured gamma ray background at Modane in histogram form: Malczeswki, Kisiel and Dorda, J. Radioanal. Nucl. Chem., 292 (2012) 751

#@energy_unit keV       ### for the first and second columns
#@limits 6 7.0 2735.0   ### number of bins, lower and upper bounds
7     250  0.65
250   500  0.17
500  1005  0.11
1005 1555  0.05
1555 2055  0.01
2055 2735  0.007
