### ISSUE TITLE
Add X-wall and gamma veto glass bulk generators

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#171]
Main wall PMT glass was added in #71 but can we get vertex generators for the X wall and veto PMT's, please? Needed for @wausain and @lecdawson 's work - @wausain should be able to test it if someone can work out how to add it.

**Comment by lemiere** [comment]
Hi,
Geometry exist, there is only vertex generator to add.
For who want a tutorial, I will fix it tomorrow.
![Capture d’écran_2020-04-06_00-49-55](https://user-images.githubusercontent.com/20680400/78511938-cb72ea00-77a0-11ea-8082-a144aaa48693.png)
![Capture d’écran_2020-04-06_00-41-45](https://user-images.githubusercontent.com/20680400/78511939-cc0b8080-77a0-11ea-850c-21676f708a85.png)
