### ISSUE TITLE
Typo in gamma_tracking_driver.cc

### ISSUE THREAD

**Issue by pfranchini** [SuperNEMO-DBD/Falaise#173]
https://github.com/SuperNEMO-DBD/Falaise/blob/77904b5bbab1f11c768055d431fc895889a4166b/modules/GammaTracking/GammaTracking/gamma_tracking_driver.cc#L76

I guess has to be the_gamma_calos.insert(std::make_pair(a_calo_hit->get_hit_id(), gt::event::calorimeter_hit()));

**Comment by drbenmorgan** [comment]
Pull requests welcome!

**Comment by drbenmorgan** [comment]
Fixed by #175
