### ISSUE TITLE
2nu excited states 82Se 0+1->0+1

### ISSUE THREAD

**Issue by cmarquet** [SuperNEMO-DBD/Falaise#187]
We need to add this generator for 2b2n excited states studies.
Support from Vladimir has been requested.

**Comment by drbenmorgan** [comment]
As this is event generation, I've _provisionally_ assigned @emchauve as he did the last PR on genbb (#180), and @cmarquet as you requested it! Just let me know if it should be reassigned!

To quickly triage, do we know:

1. Is this functionality already in Bayeux/bxdecay0 (i.e. just need to add an entry in our config files)?
2. If not, the PR to implement it on https://github.com/BxCppDev/bxdecay0 or https://github.com/BxCppDev/Bayeux should be cross-referenced here once in progress.
   - That will also imply a new tag of those packages and an update to our testing Docker images, that's fine, just need the details of the tag(s) when available.

**Comment by fmauger** [comment]
Yes, the material from Vladimir is expected for porting in BxDecay0. I hope it will be easy, depending on the computing technique used to build and integrate the phase space factor for the pair of electrons. This will trigger a new tag BxDecay0-1.0.2 (together with new support for generator with DBD gA modes) and also will request to manage some downloaded external resource files for tabulated phase space (from where: website, specific repository with public access (~500Mb)) ?. Then a new tag for Bayeux which now integrates BxDecay0 external stuff. My Bayeux devel is ready for that in principle. However I had no time to test new Boost versions  with it, nor Ubuntu 20.04 (but this last point is not that urgent). Finally only new configs in Falaise and associated doc should be needed.

**Comment by drbenmorgan** [comment]
Thanks @fmauger, once the tag of Bayeux/Bxdecay0 is ready I can prepare the new docker images for testing here. I guess that means we'll move to bxdecay0+Bayeux (fine BTW!)?

For the phase space file, we do have the supernemo.org CVMFS repository now. It's not a perfect solution, but might offer a holding place until the calculation is implemented? @pfranchini is managing that so easy to upload the data there if needed.

**Comment by fmauger** [comment]
ok for bxdecay0+Bayeux.
ok so an additional spack formula + storage of the phase space tarballs on supernemo.org ASAP.
I have requested some storage space with public web access at CCIN2P3 to publish this kind of  tarball with physics data. I wait for their answer.

**Comment by drbenmorgan** [comment]
Sounds good @fmauger! I've added you as an assignee here for notification etc, and cross referenced #172

**Comment by drbenmorgan** [comment]
@pfranchini, I know you've some experience already in uploading to the SuperNEMO CVMFS repo. Could you document the procedure, either here or as a tech note for DocDB so we got that handy should the upload discussed above be needed? Thanks!

**Comment by fmauger** [comment]
The port for 82Kr excited states has been included in BxDecay0. We have now to finalize the support for gA processes before to provide a new tag.

**Comment by drbenmorgan** [comment]
gA is now in bxdecay0, so marking this as closed - the generator will be available in Falaise from the next release (modulo patches to make it available through `flsimulate-configure`.
