### ISSUE TITLE
flvisualize can't change view on mac

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#195]
On my Mac installation, I can't switch from top to side/front view in flvisualize. I also get a LOT of error messages when I run it. It works fine for me on Lyon, where I seem to have a newer falaise (upgraded it last week but not from brew)
 
Broken one:
MacOS 10.14.5
* Falaise : 4.0.1
* Bayeux  : 3.4.1
* Boost   : 106900
* Geant4  : 9.6.4

Working one on Lyon
* Falaise : 4.0.2
* Bayeux  : 3.4.1
* Boost   : 106300

There are a load of error messages which I will paste in a comment cos they are long.

**Comment by cherylepatrick** [comment]
[flviserrors.txt](https://github.com/SuperNEMO-DBD/Falaise/files/4546015/flviserrors.txt)

That's the error output. I think it was all at startup, not when I tried to switch views, but I did try to switch views. Was using no input file but it happens when I have an input file as well.

**Comment by cherylepatrick** [comment]
It can't find this file but I don't know what the parent directory is...
inc/falaise/snemo/view/event_browser_signals.h

**Comment by drbenmorgan** [comment]
O.k., managed to reproduce locally, but as yet can't find the source of the error. If you're feeling brave,

```
$ brew unlink falaise
$ brew install falaise --HEAD
```

will install the current tip of the `develop` branch which does work. I'll try and track down the commit that fixes...

**Comment by cherylepatrick** [comment]
Oh you know I like to live dangerously... I'll give it a go. Thanks Ben.

**Comment by cherylepatrick** [comment]
It worked! Thank you!

**Comment by drbenmorgan** [comment]
As @matteoceschia also experienced this, I'm going to reopen just in case others experience it. Also means I can cross-ref and fix a PR for it!
