### ISSUE TITLE
Flreconstruct Error - Reconstructing using Falaise (and sn-flash) 

### ISSUE THREAD

**Issue by wausain** [SuperNEMO-DBD/Falaise#199]
Alongside the error #198 for simulating, reconstruction using Falaise 4.0.2 seems to be bugged.

When reconstructing, the reconstruction fails after only a few events are reconstructed and gives this error message. 

![image](https://user-images.githubusercontent.com/29455877/81180401-ddfc6100-8fa2-11ea-9414-86679a8224a8.png)

Again this worked fine for previous versions of Falaise.

Reconstruction was done using the official reconstruction (2.0.0).

**Comment by drbenmorgan** [comment]
I'll fix #198 first, but in the meantime, do you have a small file of events that can reproduce this?

**Comment by wausain** [comment]
[test.brio.zip](https://github.com/SuperNEMO-DBD/Falaise/files/4587595/test.brio.zip)

**Comment by drbenmorgan** [comment]
Thanks @wausain, I'll try and look at this ASAP.

**Comment by drbenmorgan** [comment]
Hi @wausain, that file isn't working for me - I unzip it but only get a 45B file that neither ROOT not flreconstruct can read. It should be fine to post a larger file here, or mail me with it!

**Comment by emchauve** [comment]
I also confirm similar issue with Falaise 4.0.2, while we do not have it with 4.0.0 ! There was no so much changes between both version. The only significant commit where the bug could have been introduced is there : https://github.com/SuperNEMO-DBD/Falaise/commit/bbf8312ead5bf4342e8d5da12c8fed48d256a687

**Comment by drbenmorgan** [comment]
Thanks @emchauve! If you also have a small event file, or reproducible (i.e. fixed rng seeds, small number of events) `flsimulate` input script, please post!

**Comment by emchauve** [comment]
this event has the issue  : 
[issue199event.zip](https://github.com/SuperNEMO-DBD/Falaise/files/4595048/issue199event.zip)
 
(github do not accept .brio file but fine with .zip, so I zipped it)

**Comment by drbenmorgan** [comment]
Thanks! I was able to run this through `flreconstruct` from 4.0.3 and it worked, but the current `tip` of develop failed:

``` console
$ ./BuildProducts/bin/flreconstruct -i ~/issue199event.brio -p @falaise:snemo/demonstrator/reconstruction/production.pipeline.conf
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'Falaise_CAT'...
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'TrackFit'...
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'Falaise_TrackFit'...
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'Falaise_ChargedParticleTracking'...
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'GammaTracking'...
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'Falaise_GammaClustering'...
CAT::clusterizer::initialize: Entering...
CAT::clusterizer::readDstProper: Entering...
CAT::clusterizer::readDstProper: SuperNemo kind of data
CAT::clusterizer::readDstProper: small radius 2 mm
CAT::clusterizer::readDstProper: tangent phi 20
CAT::clusterizer::readDstProper: tangent theta 160
CAT::clusterizer::readDstProper: small number 0.1 mm
CAT::clusterizer::readDstProper: quadrant angle 90
CAT::clusterizer::readDstProper: ratio 10000
CAT::clusterizer::readDstProper: compatibility distance 4
CAT::clusterizer::readDstProper: maximum chi2 3
CAT::clusterizer::readDstProper: probmin 0
CAT::clusterizer::readDstProper: first event number -1
CAT::clusterizer::readDstProper: cell pitch:  43.95 mm
CAT::clusterizer::readDstProper: verbosity print level: 2
CAT::clusterizer::readDstProper: Done.
CAT::clusterizer::initialize: Done.
CAT::sequentiator::readDstProper: SuperNemo kind of data
[fatal:virtual base_module::process_status dpp::chain_module::process(::datatools::things &):185] Module 'CATTrackerClusterizer' failed to process event record; message is '[double snemo::geometry::gveto_locator::getXCoordOfColumn(uint32_t, uint32_t, uint32_t) const:463: Invalid column number(6>0)!]'
CAT::clusterizer::finalize: Ending algorithm clusterizer...
CAT::clusterizer::finalize: Initial events:  0
CAT::clusterizer::finalize: Skipped events:  0 ( nan %)
CAT::clockable::dump: time of ' clusterizer: finalize ' : 0.026 ms (100 %)
CAT::sequentiator::finalize: Ending algorithm sequentiator
CAT::sequentiator::finalize: Initial events:  0
CAT::sequentiator::finalize: Skipped events:  0 ( nan %)
CAT::clockable::dump: time of ' sequentiator: finalize ' : 0 ms (nan %)
$
```

Could you confirm that's the output you're seeing? Also, what does `flreconstruct --version` print for you (it should print a version and git hash if it's been built from anything other than a release tarball). It's possible that you're running a commit on the `develop` branch, which would explain why I couldn't reproduce with 4.0.2. That will actually make it easier to track down!

**Comment by emchauve** [comment]
Yes this is the error. Hash is `90dd7f63` so indeed develop branch between 4.0.2 and 4.0.3

**Comment by drbenmorgan** [comment]
Tracked down to commit 42ed724b61737122fd161e2f2b180547827f07aa, needs further diagnosis on whether changes to `gveto_locator` is cause or somewhere else. All tests of the locators and modules at that commit pass, so will use @emchauve's file to prepare the test for now. If we can track down the error more specifically, then can also implement a unit test.
