### ISSUE TITLE
Flrecontruct: Particle Track Data bank issue

### ISSUE THREAD

**Issue by Tedjditi** [SuperNEMO-DBD/Falaise#201]
Hello,

I was working on the GammaTracking and GammaClustering module when i encountered a problem with the PTD bank.
After reconstructing event, the PTD is not filled and stays empty.

I work on cclyon.
My falaise installation is done by following yves "my_falaise" tutorial so i'm link to François linux brew and nemo/sw/bayeux_4.0.0 version ([setup.txt](https://github.com/SuperNEMO-DBD/Falaise/files/4591127/setup.txt))

The test i done is the following:

1) Simulate 1000 2.6MeV gamma from the source foil ([Simple_prod.txt](https://github.com/SuperNEMO-DBD/Falaise/files/4591138/Simple_prod.txt) & [Simple_Prod_profile.txt](https://github.com/SuperNEMO-DBD/Falaise/files/4591139/Simple_Prod_profile.txt))

2) Reconstruct the simulation file normally plus the GammaClustering module to insure PTD presence ([flreconstruct_gc.txt](https://github.com/SuperNEMO-DBD/Falaise/files/4591151/flreconstruct_gc.txt))

3) Check if the PTD is filled with flvisualize.

I have done the test on different version of falaise and obtained the following result:

Version 3.3.0 (ec91e92) --> Work (PTD correctly filled) (![flvisualize_v3-3-0](https://user-images.githubusercontent.com/32705205/81264331-7ea15e00-9041-11ea-9fac-3357ebea3d56.png)
)
Version 4.0.2 (90dd7f63) --> Compile but no PTD (![flvisualize_v4-0-2](https://user-images.githubusercontent.com/32705205/81264364-8c56e380-9041-11ea-9007-22d268005d5b.png)
)
Version (4.0.3) Latest --> Compile but no PTD (![flvisualize_v4-0-3](https://user-images.githubusercontent.com/32705205/81264382-9678e200-9041-11ea-8212-c20ef4c97e18.png)
)

I do not know where this problem come from. If you need more information do not hesitate to ask.

Thanks,
Tedjditi Hichem

**Comment by drbenmorgan** [comment]
Thanks @Tedjditi, I'll try and reproduce with your examples!

**Comment by drbenmorgan** [comment]
Hi @Tedjditi, I've had a quick look, and been sort of able to reproduce this, but I'm seeing the same issue as in #99, so it's possibly related.  This doesn't appear to happen on the current tip of the `develop` branch so could you try a build of that and run with your scripts above to see if that changes things please? My runs still have empty PTD banks, but at least it runs.

Is it possible to prepare an output simulation file that contains a few (i.e. less than 10) events and
for each event what data the `PTD` bank _should_ contain after running your reconstruction script? That way we'll have a known result to compare against and help track down the cause of the bug.

**Comment by Tedjditi** [comment]
when i do "git clone https://github.com/SuperNEMO-DBD/Falaise.git" i get the latest Falaise version on the develop branch no ? 

if yes, i tested it and i still have the bug. I do not see the crash mentioned in the issue #99 on cclyon.

i will provide a brio file with less event (cclyon still have some latency problem making it really uncomfortable to work on it). but basically, if you have a non-associated calorimeter hit (no trace associated) or a trace in the tracker you should have something in the PTD.

**Comment by drbenmorgan** [comment]
> i will provide a brio file with less event (cclyon still have some latency problem making it really uncomfortable to work on it). but basically, if you have a non-associated calorimeter hit (no trace associated) or a trace in the tracker you should have something in the PTD.

Hi @Tedjditi, any update on a file to exercise the bug?

**Comment by drbenmorgan** [comment]
Hi @Tedjditi, this was covered in today's Software Integration meeting and is considered a high priority fix. Could you please, as a matter of urgency, send an flsimulate output file with a handful of events that will reproduce this issue.

**Comment by willquinn** [comment]
Hi @drbenmorgan I have a file that I generated using latest develop branch. Is that what you are after?

I don't know the best way fo sharing it. On CCLyon: /sps/nemo/scratch/wquinn/rec_test.brio

**Comment by drbenmorgan** [comment]
Thanks @willquinn, how big is the file? It *should* be possible to attach small-is files (100kB or so?) here, otherwise you can send it to me through [https://files.warwick.ac.uk](https://files.warwick.ac.uk). Edit: use the "Upload a file for someone at Warwick" link!

**Comment by drbenmorgan** [comment]
Hi @willquinn, thanks, I've got the file! Could you outline which events _should_ have a PTD bank, and what the expected contents of the bank would be?

**Comment by willquinn** [comment]
I simulated 100 2nubb events from the source pads bulk using the default detector configuration (in flvisulise I didn't change anything). 

So I would say that I would expect each event to have a PTD bank. Shall I send you the simulated file as well?

**Comment by cherylepatrick** [comment]
I just took a look at Will's file. For example, the first event has a track that goes right up to a calorimeter, but they aren't associated into an electron particle. Similarly in events 3 and 4.

I tried to reconstruct this with a  version I have that I *thought* would make the PTD bank (4.0.2 (90dd7f63-dirty)) but not only did it not do so, it crashed after 34 of 100 events...

**Comment by drbenmorgan** [comment]
Yes, that would help - if you can cut it down to say 10 events, that would also help. I can see that events _do_ have a PTD bank but are empty. The bug as originally reported has _no_ PTD bank at all. 

Just seen @cherylepatrick's comment - o.k. that's good - if you can send the simulated file with the first 10 events, that looks to give enough to attempt reproduction.

NB: I think this is separate from the random crashes of GammaClustering. The algorithm looks to be non-deterministic (there's a random in there somewhere), hence that being random. The presence, or not, of PTD should be the same for all events.

**Comment by cherylepatrick** [comment]
I reconstructed the same simulated file using  4.0.1 in a singularity container and I got this (with PTD bank)

[cheryl_rec_will.brio.zip](https://github.com/SuperNEMO-DBD/Falaise/files/4812897/cheryl_rec_will.brio.zip)

**Comment by cherylepatrick** [comment]
I'm not sure about the assertion that there was no PTD bank at all in Hichem's report. If you look at his screenshots from flvis it looks the same - PTD is listed but there's nothing in it.

**Comment by cherylepatrick** [comment]
[sim_test.brio.zip](https://github.com/SuperNEMO-DBD/Falaise/files/4812905/sim_test.brio.zip)
That's the simulated file btw (I'm zipping them cos GitHub doesn't like the brio file extension)

**Comment by willquinn** [comment]
@drbenmorgan I have sent you the files, but for others they can be found at 
/sps/nemo/scratch/wquinn/sim_test_10evnts.brio
/sps/nemo/scratch/wquinn/rec_test_10evnts.brio

10 2nubb events with no PTD bank in the rec file. Each event should have a PTD bank as far as I am aware.

**Comment by drbenmorgan** [comment]
That's great, thanks both. May take a day or two to get round to looking at this, but have all I need!

**Comment by willquinn** [comment]
just to qualify as well, I used Falaise version 4.0.3
