### ISSUE TITLE
Flreconstruct failing maybe because of a gamma veto hit?

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#203]
I simulated 100 events with 1MeV electrons on the internal foil surfaces. Reconstructed with official pipeline - only 62 reconstructed. Reconstructed event 60 seemed to match simulated event 61 so it seems like it stopped part way through rather than rejected some events as it went along. I didn't see any obvious crash/error from flreconstruct, although it always prints a lot of output. Ran it twice and got the same number of events out both times. Got a lot of errors out of CAT but I also see a load of those when it reconstructs fine so don't think they are relevant. Simulated 100 more events and they reconstructed ok. Mostly just noting this here in case it's something obvious.

* Falaise : 4.0.2 (90dd7f63-dirty)
* Bayeux  : 3.4.1
* Boost   : 106900

This is the first simulated event after the reconstruction stopped, maybe the gamma veto hit is significant?
<img width="865" alt="image" src="https://user-images.githubusercontent.com/18677866/81925516-8f6d4900-95d8-11ea-97ec-0d9ae3332f20.png">

**Comment by drbenmorgan** [comment]
Probably the same as #199, could you check the output from `flreconstruct` for the error reported there?

It's fixed by #202, which is on `develop`, so updating falaise to 707e016 should resolve it is that error.

**Comment by cherylepatrick** [comment]
Oh yeah I think that is the same thing. Sorry, should have checked - in a bit of a rush today and not doing due diligence. I'll close this one.
