### ISSUE TITLE
Can't build PTD2ROOT

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#204]
Just checked it out and tried to build it but it crashed. Has anyone used it recently? Has the recent refactoring changed some of the variable names in the PTD bank?
```
/Users/cpatrick/SuperNEMO/github/PTD2Root.git/ptd2root.cpp:151:15: error: no member named 'has_particles' in
      'snemo::datamodel::particle_track_data'; did you mean 'hasParticles'?
      if (PTD.has_particles()) {
```

**Comment by drbenmorgan** [comment]
Yep, that's the case, but hopefully, the member functions should now be a bit clearer and better organised: 
https://github.com/SuperNEMO-DBD/Falaise/blob/707e016b11aba5dbc68e0aeaebf95806e83257d0/source/falaise/snemo/datamodels/particle_track_data.h#L39-L79

**Comment by cherylepatrick** [comment]
Well that's a good thing! I like clear and well organised!

I suspect this might be an issue for SensitivityModule too. Not sure I have the time to test it right now, but probably should shortly...
