### ISSUE TITLE
Flreconstruct Warnings

### ISSUE THREAD

**Issue by MHoballah** [SuperNEMO-DBD/Falaise#216]
While using Flreconstruct, I am receiving some errors (last few below). apparently this is mentioned (or similar problem) in closed issue #[199](https://github.com/SuperNEMO-DBD/Falaise/issues/199).

I am using:
* Falaise : 4.0.3 (5d64f089)
* Bayeux  : 3.4.2
* Boost   : 106900
* Geant4  : 9.6.4

falaise in sync with the main develop branch.

`CAT::CircleRegression::fit: problem: in circle regression, A nan Sw 69.4781 Swxx nan Swx nan
CAT::LinearRegression::fit: problem: linear regression sy02 nan Swxx nan delta nan
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
[warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side!
CAT::clusterizer::finalize: Ending algorithm clusterizer...
CAT::clusterizer::finalize: Initial events:  0
CAT::clusterizer::finalize: Skipped events:  0 ( -nan %)
CAT::clockable::dump: time of ' clusterizer: clusterize ' : 5859.4 ms (100 %)
CAT::clockable::dump: time of ' clusterizer: is good couplet ' : 1600.45 ms (27.3143 %)
CAT::clockable::dump: time of ' clusterizer: get near cells ' : 86.95 ms (1.48394 %)
CAT::clockable::dump: time of ' clusterizer: prepare event ' : 21.387 ms (0.365003 %)
CAT::clockable::dump: time of ' clusterizer: order cells ' : 3.926 ms (0.0670034 %)
CAT::clockable::dump: time of ' clusterizer: setup_clusters ' : 0.867 ms (0.0147967 %)
CAT::clockable::dump: time of ' clusterizer: finalize ' : 0.096 ms (0.00163839 %)
CAT::sequentiator::finalize: Ending algorithm sequentiator
CAT::sequentiator::finalize: Initial events:  0
CAT::sequentiator::finalize: Skipped events:  0 ( -nan %)
CAT::clockable::dump: time of ' sequentiator: sequentiate ' : 15719.4 ms (100 %)
CAT::clockable::dump: time of ' sequentiator: make copy sequence ' : 8277.05 ms (52.6551 %)
CAT::clockable::dump: time of ' sequentiator: clean up sequences ' : 6480.68 ms (41.2274 %)
CAT::clockable::dump: time of ' sequentiator: evolve ' : 5750.93 ms (36.585 %)
CAT::clockable::dump: time of ' sequentiator: evolve: part B ' : 4900.82 ms (31.177 %)
CAT::clockable::dump: time of ' sequentiator: manage copy sequence ' : 4765.77 ms (30.3178 %)
CAT::clockable::dump: time of ' sequentiator: pick new cell ' : 4377.34 ms (27.8468 %)
CAT::clockable::dump: time of ' sequentiator: make new sequence ' : 3597.67 ms (22.8869 %)
CAT::clockable::dump: time of ' sequentiator: make copy sequence: part A ' : 3480.87 ms (22.1439 %)
CAT::clockable::dump: time of ' sequentiator: make copy sequence: evolve ' : 3147.57 ms (20.0235 %)
CAT::clockable::dump: time of ' sequentiator: make scenarios ' : 1093.25 ms (6.95483 %)
CAT::clockable::dump: time of ' sequentiator: set free level ' : 965.719 ms (6.1435 %)
CAT::clockable::dump: time of ' sequentiator: can add family ' : 860.807 ms (5.47609 %)
CAT::clockable::dump: time of ' sequentiator: evolve: part C ' : 830.025 ms (5.28027 %)
CAT::clockable::dump: time of ' sequentiator: can match ' : 818.103 ms (5.20443 %)
CAT::clockable::dump: time of ' sequentiator: add pair ' : 449.129 ms (2.85717 %)
CAT::clockable::dump: time of ' sequentiator: copy to lfn ' : 329.18 ms (2.0941 %)
CAT::clockable::dump: time of ' sequentiator: copy sequence ' : 297.971 ms (1.89557 %)
CAT::clockable::dump: time of ' sequentiator: interpret physics ' : 284.716 ms (1.81124 %)
CAT::clockable::dump: time of ' sequentiator: copy scenario ' : 283.761 ms (1.80517 %)
CAT::clockable::dump: time of ' sequentiator: direct out of foil ' : 267.916 ms (1.70437 %)
CAT::clockable::dump: time of ' sequentiator: better scenario ' : 142.986 ms (0.909617 %)
CAT::clockable::dump: time of ' sequentiator: evolve: part B: set free level ' : 138.686 ms (0.882262 %)
CAT::clockable::dump: time of ' sequentiator: evolve: part B: noc ' : 110.464 ms (0.702725 %)
CAT::clockable::dump: time of ' sequentiator: calculate scenario ' : 34.923 ms (0.222165 %)
CAT::clockable::dump: time of ' sequentiator: good first node ' : 6.961 ms (0.0442829 %)
CAT::clockable::dump: time of ' sequentiator: evolve: part A ' : 6.032 ms (0.038373 %)
CAT::clockable::dump: time of ' sequentiator: make families ' : 5.231 ms (0.0332774 %)
CAT::clockable::dump: time of ' sequentiator: get link index ' : 2.933 ms (0.0186585 %)
CAT::clockable::dump: time of ' sequentiator: there is free sequence beginning with ' : 0.855 ms (0.00543915 %)
CAT::clockable::dump: time of ' sequentiator: make copy sequence: part A: beta ' : 0.804 ms (0.00511471 %)
CAT::clockable::dump: time of ' sequentiator: make copy sequence: part A: alpha ' : 0.477 ms (0.00303447 %)
CAT::clockable::dump: time of ' sequentiator: direct scenarios out of foil ' : 0.405 ms (0.00257644 %)
CAT::clockable::dump: time of ' sequentiator: finalize ' : 0 ms (0 %)
CAT::clockable::dump: time of ' sequentiator: match gaps ' : 0 ms (0 %)
CAT::clockable::dump: time of ' sequentiator: sequentiation ' : 0 ms (0 %)
`

and I don't know if its important, but flvisualize gives these warnings:

`[warning:datatools::properties& datatools::multi_properties::add_impl2(const string&, const string&):535] Key 'flreconstruct' will ignore meta 'flreconstruct::section' !
[warning:datatools::properties& datatools::multi_properties::add_impl2(const string&, const string&):535] Key 'flreconstruct.variantService' will ignore meta 'flreconstruct::section' !
[warning:datatools::properties& datatools::multi_properties::add_impl2(const string&, const string&):535] Key 'flreconstruct.services' will ignore meta 'flreconstruct::section' !
[warning:datatools::properties& datatools::multi_properties::add_impl2(const string&, const string&):535] Key 'flreconstruct.pipeline' will ignore meta 'flreconstruct::section' !
`

**Comment by cherylepatrick** [comment]
I tried to look for this but was kind of confused - if the vertex extrapolation driver is a separate step from track fit etc, why isn't it in Falaise/Modules? Will I ever understand how the code is arranged? :(

**Comment by yramachers** [comment]
Vertex extrapolation is one part of the Charged Particle Tracking module. The code is in that module directory.

**Comment by cherylepatrick** [comment]
Thanks @yramachers  got it :)

The "closest vertex is on the opposite side" message (Comment: "is this an error or a warning?") happens when there's a disagreement between the side reported by the geometry manager for the trajectory and the x position of an extrapolated vertex. (Side would be French vs Italian in our usual parlance, though they are called "BACK" and "FRONT" in Falaise speak: it complains if BACK matches to an x position > 0 which I *think* is France, which would imply BACK = Italy= negative x and FRONT = FRANCE = positive x? We should figure these out for definite and document them somewhere easy to find).

So far so good. How does it decide the x position of the vertex? If it's extrapolating to the source foil, it sets it to zero, so that should be OK, it's on no side. So I think these must be extrapolated to calorimeter blocks, maybe round the end of the foils, as I think it would stop if it actually hit a foil before it hit a calorimeter. This code's more impenetrable than I expected so I'm not going to look at it more right now.

As a general comment - how hard would it be when we have a warning like that to print what event it is for? It's a lot easier to diagnose a problem when we can look at the bad event, rather than just knowing that somewhere in the million events, the vertex fitter was sad. Is it possible to include that in the logging code (`DT_LOG_WARNING`), do you think?

**Comment by MHoballah** [comment]
It is hard to check the bad events as there is no leads to them inside these errors, as far as i can see. But if you look through flvisualize and the root file (created by Sensitivity module) most of the particles reconstructed are positrons, and i dont know if this is related to the problem.

I don't think that I mentioned that I am using "load_supernemo_setup_pro" for Bayeux on cc-Lyon

**Comment by MHoballah** [comment]
So, updates:

The positron problem was solved by correcting a missing "!" here:

https://github.com/SuperNEMO-DBD/Falaise/commit/9aee9ec16a9244d25d8d1df27fb7407b05e59926#diff-fd82a025a55df537d8776aa5918a07e7L146

and the warning: [warning:void snemo::reconstruction::vertex_extrapolation_driver::_measure_vertices_(const snemo::datamodel::tracker_trajectory&, snemo::datamodel::particle_track::vertex_collection_type&):350] Closest vertex is on the opposite side! 
is created from the file  Falaise/modules/ChargedParticleTracking/ChargedParticleTracking/vertex_extrapolation_driver.cc 
there the condition 
```
  if ((side == snemo::geometry::side_t::BACK && pos.x() > 0.0) ||
        (side == snemo::geometry::side_t::FRONT && pos.x() < 0.0)) {
      // Is this an error or warning?
      DT_LOG_WARNING(logPriority_, "Closest vertex is on the opposite side!");
    }
```
produces an error when the vertex is at the source foil, in this case the x is always pos.x() = 0, but the problem is that 0 is not exactly equal to 0 but some order of 10^-13, and it can be positive or negative. and this is by most part is giving the warning.  Other case of these warnings is when the vertex is reconstructed at some (random?) point far away, and these rare cases are trivial, I guess (?)

Thanks to Xavier again for the help :)

cheers,

**Comment by cherylepatrick** [comment]
@drbenmorgan @MHoballah  - do you know what the status is of getting this fix live? People have been  reporting electrons being misreconstructed as positrons (@VeronikaPalusova @willquinn ) and we initially thought it was a problem with the magnetic field... but maybe it was just this issue? It's a pretty huge deal, so we do need the fix available...

**Comment by cherylepatrick** [comment]
@wausain just tagging you in case you've inadvertently used this dodgy version... it's mixing up electrons and positrons if they have a vertex on the foil. Could be giving you wrong numbers of events passing your charge cut...

**Comment by MHoballah** [comment]
Hello, I didn't personally change anything live nor have I received anything about fixing in new versions. 
I have noticed that the link does get you directly to the problem so here it is : 

modules/ChargedParticleTracking/ChargedParticleTracking/charge_computation_driver.cc
in the above file (existent in the link), if you go to line  146 : (!_charge_from_source_) and what is updated (chargeFromSource_), there is a missing "!" in the update. If you just change this in  your file your problem is solved.

**Comment by emchauve** [comment]
I made the pull request to fix this typo introduced by "modernization" stuff
https://github.com/SuperNEMO-DBD/Falaise/commit/9aee9ec16a9244d25d8d1df27fb7407b05e59926#diff-191f301098dec10325f1bbfbecdc51749a7b0dba46dcb12feefdeb027a906c4e
