### ISSUE TITLE
tweakable_generator  - tabulated function error

### ISSUE THREAD

**Issue by VeronikaPalusova** [SuperNEMO-DBD/Falaise#217]
I'm trying to test the tweakable generator with `generator/if_tweakable/energy_mode/if_spectrum/mode = "tabulated_function"` option using this example file: https://github.com/fmauger/Falaise/blob/0df5b0303a24cc62ae798fce28b361a2bc131bc9/resources/config/snemo/demonstrator/simulation/primary_events/1.3/data/energy_spectrum-example-1.data

This is the relevant part of my variant.profile generated from flsimulate-configure:
```
[registry="primary_events"]
generator = "tweakable_generator"
generator/if_tweakable/particle = "neutron"
generator/if_tweakable/energy_mode = "spectrum"
generator/if_tweakable/energy_mode/if_spectrum/mode = "tabulated_function"
generator/if_tweakable/energy_mode/if_spectrum/file = "my_falaise/energy_spectrum-example-1.data"
generator/if_tweakable/direction_mode = "randomized"
```

However, I get the following message: 
``` 
flsimulate : Setup/run of simulation threw exception
[void genbb::single_particle_generator::_init_energy_spectrum():970: Format error in interpolation data file 'my_falaise/energy_spectrum-example-1.data' !] 
```

flsimulate uses the following external libraries:

- Falaise : 4.0.2 
- Bayeux : 3.4.1
- Boost : 106300
- Geant4 : 9.6.4

Any help is appreciated

**Comment by emchauve** [comment]
try to remove the last line with `(END) `at the end the file `energy_spectrum-example-1.data` ?
