### ISSUE TITLE
Debian 10: Install (again)

### ISSUE THREAD

**Issue by edbird** [SuperNEMO-DBD/Falaise#220]
Sorry I know I've asked about this before, but I can't remember what went wrong last time, what the fix was etc... Also tried looking for previous issues - thought I had raised one - but couldn't find it.

![image](https://user-images.githubusercontent.com/2939755/94577531-9dadc000-026e-11eb-9e60-e1619915c589.png)
![image](https://user-images.githubusercontent.com/2939755/94577584-aa321880-026e-11eb-9f52-f915e973e57c.png)
![image](https://user-images.githubusercontent.com/2939755/94577619-b1f1bd00-026e-11eb-9a82-51a106bd6c1a.png)
![image](https://user-images.githubusercontent.com/2939755/94577681-bfa74280-026e-11eb-9d32-245ea7342972.png)

What should I check first? Presumably some log files somewhere?

**Comment by drbenmorgan** [comment]
https://github.com/SuperNEMO-DBD/brew/issues/27
https://github.com/SuperNEMO-DBD/brew/issues/30

**Comment by edbird** [comment]
@drbenmorgan Thanks for these, I'd forgotten they were posted on the other repository...

However it appears to be a different issue this time, should I raise a new issue there?

Here is the gistlog token: https://gist.github.com/edbird/5046be74bb04639bfbce54440988a627

Generated using `brew gist-logs xz`

Not 100 % sure if this is the right thing to have run?

The m4 issue has been patched since I last had problems.

Having followed the other issues raised previously I'm seeing the same output as before. (Not unexpected)

![image](https://user-images.githubusercontent.com/2939755/94681142-d86d3200-031a-11eb-9e68-f544bab9a48c.png)

**Comment by drbenmorgan** [comment]
Closing as this an unsupported platform and there is no spare time to address adding Debian support.
