### ISSUE TITLE
Supposedly invalid dimension in copper source foil

### ISSUE THREAD

**Issue by fmauger** [SuperNEMO-DBD/Falaise#230]
Having a deeper look on the new geometry models of the "realistic but still flat" source foils, I have noticed that the Copper strips are 74.0 microns thick (https://github.com/SuperNEMO-DBD/Falaise/blob/develop/resources/snemo/demonstrator/geometry/GeometryModels/source_module/flat/source_foils.geom, line 33). However, the parent "snemo_source_0.model" was made  x=43.0 um thick (line 41) which is not compatible with the thickness of the copper foil "internal_item" which should be contained without overlapping. This should be changed to at least x=74 um (and < 58 mm , thickness of the source frame) to guarantee the consistency of the geometry model for GDML and G4 (otherwise it may cause tracking issues/crash).

**Comment by fmauger** [comment]
And also the "[name="snemo_source_17.model" type="geomtools::stacked_model"]"  definition at line 722 lacks the  "#@description ITEP-10" following directive for clarity.

**Comment by fmauger** [comment]
And also also I do not understand why there is a "source_module" subdirectory in the "source_module" directory with somewhat similar contents ! It seems not to be addressed in the "resources/snemo/demonstrator/geometry/GeometryModels/Demonstrator.conf" main file.

**Comment by fmauger** [comment]
Also^3 : The positioning of "bottom_film" and "top_film" in the "snemo_source_0.model" and "snemo_source_35.model" models is wrong. The Z coordinates should be -1462.5mm and +1462.5mm respectively to ensure a cumulative height of 3350mm with the 2500mm copper foils
with NO z-overlap.
Formula: along z, 425mm+2500mm+425mm=3350mm
So z pos is +/- (2500mm/2+425mm/2)=1462mm

``` 
        bottom_film                  source_0_0                 top_film
          (mylar)                     (copper)                  (mylar)  
-------[-----+-----][--------------------+-------------------][-----+-----]--------------------> z
           -1462                         0                         +1462
```
To be assigned to @lemiere

**Comment by lemiere** [comment]
`#@description ITEP-10` added
"source_module" subdirectory in the "source_module" directory  deleted
 "snemo_source_0.model"  thickness adapted

Copper foil is 2490 mm long so to  ensure a full foil lenght at 3350 mm, film lenght should be 430 mm and then the placement is +/- 1460 mm. --> fixed

Copper foil width is 12.2 cm instead of 12.5 cm in the conf file --> fixed

**Comment by cherylepatrick** [comment]
Hi @fmauger and @lemiere  and thanks for testing/fixing. Can I just check the implications of this? 

- Is the copper foil actually wrongly modelled, or is it just some internal thing that needs to be consistent? I think if I read it correctly that you've changed the dimensions in the y-z plane?
- Does the "#@description ITEP-10" affect the functionality, or is that a readability thing?

@willquinn wants to do some sensitivity testing of the new geometry - should he be using pull request #231 as his Falaise version? And are there some quick basic tests of this fix that he can do  while he's got it checked out? Let us know!

**Comment by fmauger** [comment]
> Hi @fmauger and @lemiere and thanks for testing/fixing. Can I just check the implications of this?
> 
>     * Is the copper foil actually wrongly modelled, or is it just some internal thing that needs to be consistent? I think if I read it correctly that you've changed the dimensions in the y-z plane?

both.
but the change in dimension is tiny with no expected implications unless you are interested in some events at the edges of the copper foils... which I guess is of  no interest ;-).
some placements were incorrect but have not triggered some G4 crash so far. However better to fix it now it has been detected.

> 
>     * Does the "#@description ITEP-10" affect the functionality, or is that a readability thing?

no effect. only readability.

> 
> 
> @willquinn wants to do some sensitivity testing of the new geometry - should he be using pull request #231 as his Falaise version? And are there some quick basic tests of this fix that he can do while he's got it checked out? Let us know!
In principle , we expect no impact on Will's studies because there is no expected effects induced by the Copper foil geometry (unless an geometry overlap during G4 tracking but probably extremely rare). so he can run with the current setup.

**Comment by lemiere** [comment]
It's only tiny changes.... PR is big mess for so small stuff ;-)
Quick merge will allow @willquinn  to play with.

**Comment by cherylepatrick** [comment]
Thank you! That's what I like to hear :)

**Comment by drbenmorgan** [comment]
I've reopened and linked to #231 - just for bookkeeping and clarity!

That looks o.k. and ready for merge on reviewer approval.

**Comment by cherylepatrick** [comment]
Thanks for the explanation! Sounds like the tiny dimension changes aren't a huge deal but it's better to have them right. Only thing that looks like it might be dramatic is this:
```
[name="snemo_source_0.model" type="geomtools::simple_shaped_model"]
 shape_type         : string  = "box"
 x                  : real    =   43.0 um
 x                  : real    =   1.0 cm
```

But that's just the change to make sure Geant doesn't crash?

As far as I'm concerned it looks OK to merge, and Will can give it a test.
