### ISSUE TITLE
"Go to event number" option in flvisualize

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#24]
Would it be possible to add a "go to event number xxx" facility in flvisualize? As far as I can see, the only ways to change the event you are looking at are with the "next event" button or with the drop-down list. With a big file (e.g. 1 million events) it can take minutes of scrolling to get to the event you want. It would be nice to be able to type in a number and immediately go to that event.

Alternatively, being able to supply flvisualize with a list of event numbers you are interested in, and for the dropdown and next/previous buttons to only move through that list would be even better, but that sounds difficult!

**Comment by xgarrido** [comment]
Event header cut allows to select events given a list of run/event id number. To use it within ```flvisualize``` you need to enable the Complex selection box. Nevertheless, to achieve it you have to first give a cut manager to ```flvisualize```. For instance, here is a minimal example of what a cut manager configuration file should contain 

```
#@description Logging priority
logging.priority : string = "error"

#@description A list of files that contains definition of cuts
cuts.configuration_files : string[1] as path = "event_header_cuts.conf"
```
and the ```event_header_cuts.conf``` file can hold for example such selection cut

```
#@description A sample list of setups
#@key_label   "name"  
#@meta_label  "type"   

[name="list_of_ids_cut" type="snemo::cut::event_header_cut"]  

#@description Cut description
cut.description : string = "Select event following a list of event ids"  

#@description Logging priority    
logging.priority : string = "error"

#@description The label/name of the event header' bank (mandatory)   
EH_label : string = "EH" 

#@description Activate list of event ids mode 
mode.list_of_event_ids : boolean = true  

#@description Filename with event id 
list_of_event_ids.ids : string[5] = "0_3"  "0_7"  "0_15" "0_25" "0_69" 
```          
where event ids list is ```RunNumber_EventNumber```. For simulation, run id is always 0 and with the cut above you will only select event 3, 7, 15, 25 and 69.

Then you need to pass the cut manager to ```flvisualize``` using option --cut-config-file i.e.
```
$ flvisualize -i sim.brio --cut-config-file cut_manager.conf
```
and you will be able to enable Complex selection and select the ```list_of_ids_cut``` in the combo box under selection tab.

**Comment by drbenmorgan** [comment]
As the primary request is met by #42, I'm closing this issue - #35 is an additional enhancement!
