### ISSUE TITLE
Allow flsimulate to load module plugins

### ISSUE THREAD

**Issue by pguzowski** [SuperNEMO-DBD/Falaise#31]
So that for example people can write their own event generators and run them with flsimulate.

The functionality would be similar to that what already exists for flreconstruct.

**Comment by drbenmorgan** [comment]
Could you outline the uses cases and requirements in a bit more detail please? As #29 and #30 show, event generators can be added easily through config/variants.

What specific event generators are required, and similarly, what other types of module would you want to allow?

**Comment by pguzowski** [comment]
A reminder that I'm running as a (semi?) end-user, not a developer, I have installed bayeux & falaise with cadfaelbrew (I cannot modify or add any code there), so I want to write my own plugin module as can [already be done for flreconstruct](https://supernemo-dbd.github.io/Falaise/writingflreconstructmodules.html).

While tinkering around trying things for #25 I have written two new classes, one extending genbb::i_genbb for the decay generation, and one extending genvtx::i_vertex_generator for the vertex generation. I want to compile these into a standalone library and load them into flsimulate. As mentioned this sort of situation can already be done with flreconstruct.

Other use cases: 
- Simulation of quadruple-beta decay. 
- Our first-year student will be studying Lorentz-violating decays.
- I wanted to look at the SuperNEMO sensitivity to solar axion interactions.
- Some theorist tomorrow could come up with a relevant new physics model, and we would want to start simulating it straight away.

These sort of studies cannot be done with single-particle generators or other proposed solutions for #29 or #30. Even producing some sort of generic multi-particle generator would quickly become extremely complex & unwieldy, with respect to energy/angular/timing spectra and correlations.

Ideally you would want (semi?) end-users to write their own generators, or wrap a third-party generator library within the genbb/genvtx context, and load them as a module. If there is a demand for wider collaborative use of these specific cases, these should really be standalone modules downloadable from github, rather than part of the core falaise installation. That way they are not chained to the release cycle of falaise.

**Comment by drbenmorgan** [comment]
Thanks @pguzowski that illustrates things very clearly!

I think this can be done, though I think the main challenge will be to make this play nicely with the variant/config system. I can dig into this a bit more, together with the simulation and event/vertex generator, to prepare a design.

**Comment by drbenmorgan** [comment]
Closing in favour of custom simulation module, which can be integrated in flreconstruct and/or Art.
