### ISSUE TITLE
Tracker reconstruction not working for Bi207 calibration simulation

### ISSUE THREAD

**Issue by pguzowski** [SuperNEMO-DBD/Falaise#4]
I have the following configuration script:

```
#@description a short description of the simulation run`
#@key_label  "name"
#@meta_label "type"


[name="flsimulate" type="flsimulate::section"]
numberOfEvents : integer = 100

[name="flsimulate.variantService" type="flsimulate::section"]
settings : string[3] = "primary_events:generator=Bi207" \
    "vertexes:generator=source_calibration_all_spots" \
    "geometry:layout/if_basic/source_calibration=true"
```

After flsimulate and flreconstruct, there is no tracker clustering or tracker trajectory data, even for events with electrons in the event display.
![bi207_reco](https://cloud.githubusercontent.com/assets/22715780/26054162/84ea993a-3963-11e7-9779-adb522d41afd.png)

The tracker reconstruction works if this is used instead, so it is a problem specific to the calibration setup:
```
[name="flsimulate.variantService" type="flsimulate::section"]
settings : string[3] = "primary_events:generator=Se82.0nubb" \
    "vertexes:generator=source_pads_bulk" \
    "geometry:layout/if_basic/source_calibration=false"
```

Edit: I've actually narrowed this down to only happening when `primary_events:generator=Bi207` regardless of the rest of the configuration

**Comment by pguzowski** [comment]
Actually I have found an event where the reconstruction worked:
![bi207_worked](https://cloud.githubusercontent.com/assets/22715780/26055619/936c73ce-3969-11e7-990c-d8ce5fd67b52.png)



I have narrowed down the problem being due to delayed electrons
(the smallest delay I have found where the reconstruction failed, is 99ms between the electron and the original bi207 decay)

**Comment by pguzowski** [comment]
I've narrowed this down to delayed `snemo::datamodel::calibrated_tracker_hit` hits not having a valid radius...

**Comment by drbenmorgan** [comment]
Closing due to lack of updates and manpower.
