### ISSUE TITLE
Out of date Falaise Install Instructions since migration from SVN to GIT

### ISSUE THREAD

**Issue by edbird** [SuperNEMO-DBD/Falaise#43]
The instructions accessible at this location
https://supernemo-dbd.github.io/Falaise/flinstallguide.html
are out of date since the migration from SVN to GIT.

I have never logged an issue on github before so if I did this wrong please let me know by either contacting me on the software channel or by emailing edward.birdsall@postgrad.manchester.ac.uk
thank you.

**Comment by drbenmorgan** [comment]
Resolved in #49
