### ISSUE TITLE
flptd2root.py segmentation violation

### ISSUE THREAD

**Issue by lecdawson** [SuperNEMO-DBD/Falaise#46]
Hi,
I have been trying to run flptd2root.py on reconstructed files that include gamma tracking. This should be possible as Cheryl has successfully run the code on her mac. I have recently upgraded falaise but I get the following error when I run the script:

Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170509-83837-laq70k/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170509-83837-laq70k/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TArrayCMod read from file Tl208_1M_flrec2_1.brio
   has the same version (=1) as the active class but a different checksum.
   You should update the version to ClassDef(TArrayCMod,2).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   char* fArray; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   int fCapacity; //
[notice:void datatools::library_loader::init():450] Automatic loading of library 'PTD2Root'...

 *** Break *** segmentation violation
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]
[<unknown binary>]

Any suggestions as to how I can fix this issue?

**Comment by cherylepatrick** [comment]
Hi Lauren, just trying to remember - did you also try it on a file that didn't include gamma tracking, with the same result? I think yes?

**Comment by lecdawson** [comment]
Hi Cheryl, yes I did. Same problem regardless if gamma tracking is included.

**Comment by drbenmorgan** [comment]
Please raise this in the https://github.com/SuperNEMO-DBD/PTD2Root issue tracker
