### ISSUE TITLE
Flvisualize side/front  view not working in Falaise 3

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#5]
On Mac OSX Sierra: I can't switch to the side or front views in flvisualize (top view looks ok). Tried it both with an xml file generated by Falaise 3 flsimulate, and with an old brio file I generated in Falaise 2. Same problem both times.

Don't know if it's related but I also get a lot of errors when I run flvisualize, will paste as a comment.

**Comment by cherylepatrick** [comment]
eduroam-int-dhcp-97-252-40:testfalaise3 cpatrick$ flvisualize -i example.xml 
[notice:void FLVisualize::do_postprocess_input_metadata(FLVisualize::FLVisualizeArgs &):98] Fetching input metadata from input data file...
[DEVEL] flVisParameters.inputMetadata:
[DEVEL] |-- Key label    : "name"
[DEVEL] |-- Meta label   : "type"
[DEVEL] |-- Entries      : <empty>
[DEVEL] `-- Ordered entries      : <empty>
[notice] Loaded input metadata: 
[notice] |-- Description  : Bayeux/dpp library's I/O module metadata store
[notice] |-- Key label    : "name"
[notice] |-- Entries      : [4]
[notice] |   |-- Entry : "flsimulate"
[notice] |   |   |-- Key        : "flsimulate"
[notice] |   |   |-- Meta       : "flsimulate::section"
[notice] |   |   `-- Properties : [10]
[notice] |   |       |-- Description  : 'flsimulate basic system informations'
[notice] |   |       |   |-- Short description : 'flsimulate basic system informations'
[notice] |   |       |   `-- Auxiliary descriptions : <none>
[notice] |   |       |-- Name : 'application'
[notice] |   |       |   |-- Description  : 'The simulation application used to produce Monte Carlo data'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : 'flsimulate'
[notice] |   |       |-- Name : 'application.version'
[notice] |   |       |   |-- Description  : 'The version of the simulation application'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : '3.0.0'
[notice] |   |       |-- Name : 'bayeux.version'
[notice] |   |       |   |-- Description  : 'Bayeux version'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : '3.0.0'
[notice] |   |       |-- Name : 'doDigitization'
[notice] |   |       |   |-- Description  : 'Activate digitization'
[notice] |   |       |   |-- Type  : boolean (scalar)
[notice] |   |       |   `-- Value : 0
[notice] |   |       |-- Name : 'doSimulation'
[notice] |   |       |   |-- Description  : 'Activate simulation'
[notice] |   |       |   |-- Type  : boolean (scalar)
[notice] |   |       |   `-- Value : 1
[notice] |   |       |-- Name : 'embeddedMetadata'
[notice] |   |       |   |-- Description  : 'Metadata embedding flag'
[notice] |   |       |   |-- Type  : boolean (scalar)
[notice] |   |       |   `-- Value : 1
[notice] |   |       |-- Name : 'experimentalSetupUrn'
[notice] |   |       |   |-- Description  : 'Experimental setup URN'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : 'urn:snemo:demonstrator:setup:1.0'
[notice] |   |       |-- Name : 'falaise.version'
[notice] |   |       |   |-- Description  : 'Falaise version'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : '3.0.0'
[notice] |   |       |-- Name : 'numberOfEvents'
[notice] |   |       |   |-- Description  : 'Number of simulated events'
[notice] |   |       |   |-- Type  : integer (scalar)
[notice] |   |       |   `-- Value : 1
[notice] |   |       `-- Name : 'userProfile'
[notice] |   |           |-- Description  : 'User profile'
[notice] |   |           |-- Type  : string (scalar)
[notice] |   |           `-- Value : 'normal'
[notice] |   |-- Entry : "flsimulate.simulation"
[notice] |   |   |-- Key        : "flsimulate.simulation"
[notice] |   |   |-- Meta       : "flsimulate::section"
[notice] |   |   `-- Properties : [2]
[notice] |   |       |-- Description  : 'Simulation setup parameters'
[notice] |   |       |   |-- Short description : 'Simulation setup parameters'
[notice] |   |       |   `-- Auxiliary descriptions : <none>
[notice] |   |       |-- Name : 'rngSeeding'
[notice] |   |       |   |-- Description  : 'PRNG initial seeds'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : '{EG=35139597; MGR=577503205; SHPF=1043267378; VG=907879440}'
[notice] |   |       `-- Name : 'simulationSetupUrn'
[notice] |   |           |-- Description  : 'Simulation setup URN'
[notice] |   |           |-- Type  : string (scalar)
[notice] |   |           `-- Value : 'urn:snemo:demonstrator:simulation:2.1'
[notice] |   |-- Entry : "flsimulate.variantService"
[notice] |   |   |-- Key        : "flsimulate.variantService"
[notice] |   |   |-- Meta       : "flsimulate::section"
[notice] |   |   `-- Properties : [2]
[notice] |   |       |-- Description  : 'Variant setup'
[notice] |   |       |   |-- Short description : 'Variant setup'
[notice] |   |       |   `-- Auxiliary descriptions : <none>
[notice] |   |       |-- Name : 'configUrn'
[notice] |   |       |   |-- Description  : 'Variants setup configuration URN'
[notice] |   |       |   |-- Type  : string (scalar)
[notice] |   |       |   `-- Value : 'urn:snemo:demonstrator:simulation:2.1:variants'
[notice] |   |       `-- Name : 'profileUrn'
[notice] |   |           |-- Description  : 'Variants profile URN'
[notice] |   |           |-- Type  : string (scalar)
[notice] |   |           `-- Value : 'urn:snemo:demonstrator:simulation:2.1:variants:profiles:default'
[notice] |   `-- Entry : "flsimulate.services"
[notice] |       |-- Key        : "flsimulate.services"
[notice] |       |-- Meta       : "flsimulate::section"
[notice] |       `-- Properties : [1]
[notice] |           |-- Description  : 'Services configuration'
[notice] |           |   |-- Short description : 'Services configuration'
[notice] |           |   `-- Auxiliary descriptions : <none>
[notice] |           `-- Name : 'configUrn'
[notice] |               |-- Description  : 'Services setup configuration URN'
[notice] |               |-- Type  : string (scalar)
[notice] |               `-- Value : 'urn:snemo:demonstrator:simulation:2.1:services'
[notice] `-- Ordered entries      : [4]
[notice]     |-- Entry [rank=0] : "flsimulate"
[notice]     |-- Entry [rank=1] : "flsimulate.simulation"
[notice]     |-- Entry [rank=2] : "flsimulate.variantService"
[notice]     `-- Entry [rank=3] : "flsimulate.services"
[notice:void FLVisualize::do_postprocess_input_metadata(FLVisualize::FLVisualizeArgs &):117] Found input metadata
Input metadata of interest: 
|-- userProfile           = normal
|-- experimentalSetupUrn  = urn:snemo:demonstrator:setup:1.0
|-- variantConfigUrn      = 
|-- variantConfigPath     = 
|-- variantProfileUrn     = 
|-- variantProfilePath    = 
|-- servicesConfigUrn     = 
|-- servicesConfigPath    = 
|-- numberOfEvents        = 1
|-- doSimulation          = true
|-- simuSetupUrn          = urn:snemo:demonstrator:simulation:2.1
|-- doDigitization        = false
|-- digiSetupUrn          = 
|-- doReconstruction      = false
`-- recSetupUrn           = 
[notice:void FLVisualize::do_postprocess_input_metadata(FLVisualize::FLVisualizeArgs &):125] Input metadata from the experimental setup identifier (URN) is 'urn:snemo:demonstrator:setup:1.0'.
[notice:void FLVisualize::do_postprocess_input_metadata(FLVisualize::FLVisualizeArgs &):147] The experimental setup identifier (URN) is set to 'urn:snemo:demonstrator:setup:1.0' from input metadata.
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):173] Add input data file 'example.xml'
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):210] Using experimental setup URN='urn:snemo:demonstrator:setup:1.0'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):239] Services configuration URN='urn:snemo:demonstrator:setup:1.0:services'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):267] Services configuration path='@falaise:config/snemo/demonstrator/setup/1.0/services.conf'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):284] Geometry configuration URN='urn:snemo:demonstrator:geometry:4.0'...
[devel] geometryConfigUrnInfo: 
[devel] |-- URN : 'urn:snemo:demonstrator:geometry:4.0'
[devel] |-- Category : 'configuration'
[devel] |-- Description : SuperNEMO demonstrator geometry setup (version 4.0)
[devel] |-- Components : [2]
[devel] |   |-- Topic 'experiment' : [1]
[devel] |   |   `-- Component : 'urn:snemo:demonstrator'
[devel] |   `-- Topic 'variants' : [1]
[devel] |       `-- Component : 'urn:snemo:demonstrator:geometry:4.0:variants'
[devel] `-- Locked : true
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):299] Resolved geometry configuration path='@falaise:config/snemo/demonstrator/geometry/4.0/manager.conf'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):314] Geometry configuration path='@falaise:config/snemo/demonstrator/geometry/4.0/manager.conf'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):335] Variant configuration URN='urn:snemo:demonstrator:setup:1.0:variants'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):345] Resolving variant configuration URN='urn:snemo:demonstrator:setup:1.0:variants'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):365] Variant configuration path='@falaise:config/snemo/demonstrator/setup/1.0/variants/repository.conf'...
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):377] No variant profile is set.
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):379] No variant profile URN is set.
[notice:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):382] Trying to find a default one from the current variant setup...
[notice] Variant configuration URN info: 
[notice] |-- URN : 'urn:snemo:demonstrator:setup:1.0:variants'
[notice] |-- Category : 'variant'
[notice] |-- Description : Variants setup for the SuperNEMO demonstrator detector setup (version 1.0)
[notice] |-- Components : [3]
[notice] |   |-- Topic 'default_profile' : [1]
[notice] |   |   `-- Component : 'urn:snemo:demonstrator:setup:1.0:variants:profiles:default'
[notice] |   `-- Topic 'profiles' : [2]
[notice] |       |-- Component : 'urn:snemo:demonstrator:setup:1.0:variants:profiles:basic-1.0.0'
[notice] |       `-- Component : 'urn:snemo:demonstrator:setup:1.0:variants:profiles:hc-1.0.0'
[notice] `-- Locked : true
[warning:static void FLVisualize::FLVisualizeArgs::do_postprocess(FLVisualize::FLVisualizeArgs &):413] No variant profile is provided.
FLVisualize parameters: 
|-- logLevel             = notice
|-- libraries            = [0]
|-- experimentalSetupUrn = urn:snemo:demonstrator:setup:1.0
|-- variantConfigUrn     = urn:snemo:demonstrator:setup:1.0:variants
|-- variantConfig        = @falaise:config/snemo/demonstrator/setup/1.0/variants/repository.conf
|-- variantProfileUrn    = 
|-- variantProfile       = 
|-- servicesConfigUrn    = urn:snemo:demonstrator:setup:1.0:services
|-- servicesConfig       = @falaise:config/snemo/demonstrator/setup/1.0/services.conf
|-- ignoreInputMetadata  = false
|-- inputMetadataFile    = 
|-- inputFile            = example.xml
`-- inputMetadata        = [4]
[notice:falaise::exit_code FLVisualize::do_flvisualize(int, char **):126] Configuring browser...
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170510-77836-4va8dm/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170510-77836-4va8dm/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h
   requested to autoload type snemo::visualization::view::event_browser
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h
   requested to autoload type snemo::visualization::view::display_3d
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h
   requested to autoload type snemo::visualization::view::display_2d
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h
   requested to autoload type snemo::visualization::view::display_options
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h
   requested to autoload type snemo::visualization::view::browser_tracks
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h
   requested to autoload type snemo::visualization::view::event_selection
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h
   requested to autoload type snemo::visualization::view::progress_bar
[notice:void snemo::visualization::view::style_manager::_read_style_file_(const std::string &):401] Opened /Users/cpatrick/CadfaelBrew/Cellar/falaise/3.0.0/share/Falaise-3.0.0/resources/modules/EventBrowser/styles/snemo_demonstrator_default.sty

	SuperNEMO Event Browser                          
	Version 3.0.0
                                                   
	Copyright (C) 2010-2017                          
	SuperNEMO Collaboration                          
                                                   
	Compiled with ROOT v6.08/06

libFalaise_EventBrowser dictionary payload:7:10: fatal error: 
      '/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h'
      file not found
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrow...
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class snemo::visualization::view::event_browser with content:

#line 1 "libFalaise_EventBrowser dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class snemo::visualization::view::event_browser is available even though it has a TClass initialization routine.
Error in <TQObject::CheckConnectArgs>: signal snemo::visualization::view::event_browser::CloseWindow() does not exist
libFalaise_EventBrowser dictionary payload:7:10: fatal error: 
      '/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h'
      file not found
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrow...
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class snemo::visualization::view::display_2d with content:

#line 1 "libFalaise_EventBrowser dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class snemo::visualization::view::display_2d is available even though it has a TClass initialization routine.
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_2d::process_option_buttons() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_2d::process_option_buttons() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_2d::process_option_buttons() does not exist
libFalaise_EventBrowser dictionary payload:7:10: fatal error: 
      '/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h'
      file not found
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrow...
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class snemo::visualization::view::browser_tracks with content:

#line 1 "libFalaise_EventBrowser dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class snemo::visualization::view::browser_tracks is available even though it has a TClass initialization routine.
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::browser_tracks::item_checked(TObject*,bool) does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::browser_tracks::item_selected(TGListTreeItem*,int) does not exist
libFalaise_EventBrowser dictionary payload:7:10: fatal error: 
      '/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h'
      file not found
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrow...
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class snemo::visualization::view::display_options with content:

#line 1 "libFalaise_EventBrowser dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class snemo::visualization::view::display_options is available even though it has a TClass initialization routine.
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_volume_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_particle_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_button_misc_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_combo_misc_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_combo_misc_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::process_auto_reading() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::do_slider(int) does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::reload_style_settings() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::display_options::save_style_settings() does not exist
libFalaise_EventBrowser dictionary payload:7:10: fatal error: 
      '/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h'
      file not found
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrow...
         ^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class snemo::visualization::view::event_selection with content:

#line 1 "libFalaise_EventBrowser dictionary payload"

#ifndef G__VECTOR_HAS_CLASS_ITERATOR
  #define G__VECTOR_HAS_CLASS_ITERATOR 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_browser.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_3d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_2d.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/display_options.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/browser_tracks.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/event_selection.h"
#include "/tmp/falaise-20170510-81056-1mq6kyg/Falaise-3.0.0/modules/EventBrowser/include/falaise/snemo/view/progress_bar.h"

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class snemo::visualization::view::event_selection is available even though it has a TClass initialization routine.
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
Error in <TQObject::CheckConnectArgs>: slot snemo::visualization::view::event_selection::process() does not exist
[warning:void cuts::cut_manager::initialize(const datatools::properties &):215] No service manager configuration property !
[warning:void cuts::cut_manager::initialize(const datatools::properties &):231] No service manager is available ! This could forbid the use of some cuts !
[notice:void snemo::visualization::view::event_browser::initialize_event_server():258] Identified input data as: 'BOOST/Serialization'  (sequential reading mode)
[notice:falaise::exit_code FLVisualize::do_flvisualize(int, char **):156] Browser runs here...

**Comment by drbenmorgan** [comment]
@cherylepatrick I've triaged this to the dictionary for the EventBrowser hardcoding in paths to the headers. Everything works if Falaise is built locally, then installed. If the build/source dirs of Falaise are then moved or removed (as is the case for a package manager install), the error reported above occurs. See [here](https://root-forum.cern.ch/t/rootcling-automatically-hard-coding-build-directory-include-paths/22353) for context.

It looks a reasonably straightforward fix, but needs further testing first. I'll then submit a PR and also update the `falaise` formula so latest merged changes can be installed.

**Comment by cherylepatrick** [comment]
Thank you very much @drbenmorgan - crossing fingers that the testing comes out OK!

**Comment by drbenmorgan** [comment]
This should now be available for use by installing the `HEAD` version of falaise. If you do:

```console
$ brew update
$ brew upgrade falaise --HEAD
```

the tip of the develop branch with this fix in should be installed. See the [homebrew-cadfael README](https://github.com/SuperNEMO-DBD/homebrew-cadfael#development-versions) of details on how to manage these installs.

The fix should resolve the issue, but I'll leave this issue open until that's confirmed.

**Comment by cherylepatrick** [comment]
Thank you @drbenmorgan , trying it now!

**Comment by cherylepatrick** [comment]
Works fine on my mac! Will try updating the linux system now (that's been more weird and flaky so far).

**Comment by cherylepatrick** [comment]
Works on SL6 too, thank you very much!
