### ISSUE TITLE
Add and track metadata in input/output files

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/Falaise#57]
As discussed in the AB meeting, we need to confirm the creation, addition and management of metadata from production (MC/Raw) through to the end of reconstruction (and probably beyond). There are some checks to do first of all:

* [ ] Check that `flsimulate` stores all needed metadata into output data file, and optionally also into an additional metadata file
* [ ] Check that `flreconstruct` propagates any metadata from the input file to the output file
* [ ] Check that `flreconstruct` stores any reconstruction metadata (e.g. which processing modules/parameters were used)

We also need an interface so that any "Falaise" files can be queried for the contained metadata, e.g. print it to screen or to file.

This is coupled to Issues #33, #15

**Comment by cherylepatrick** [comment]
As suggested by @drbenmorgan (thanks Ben), adding my request from #84 to this issue:

I'd like to be able to take metadata from the simulated/reconstructed files I use for analysis, and extract it to the root file produced by SensitivityModule (so we can always be sure of exactly what we are looking at when we run analysis). Examples of what I'd like to be able to store would be:

- Version of Falaise it was simulated/reconstructed with
- Simulation parameters (e.g. vertex generator, primary event type)
- Versions of reconstruction modules it has passed through or some kind of unique identifier for the pipeline script maybe?

**Comment by drbenmorgan** [comment]
This will be migrated to the new Impressionist framework, likely using Art's Provenance tracking mechanism. I'll leave this open for now until we get an issue up on SuperNEMO-DBD/Impressionist
