### ISSUE TITLE
Documentation - vertex generators in flsimulate

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#58]
Let's collate the documentation for the vertex generators in flsimulate. At the moment it is a bit spread out over various locations and it is not easy to find out the precise detector location for all the many vertex generators. In some cases a diagram might be helpful.

We should also review the rest of the flsimulate configuration parameters and see if there's anything else in there that isn't completely self-explanatory.

**Comment by drbenmorgan** [comment]
Related to: #57

**Comment by cherylepatrick** [comment]
Good places to start:
Falaise/install/share/Falaise-3.0.0/resources/config/snemo/demonstrator/simulation/vertexes
Falaise/trunk/documentation/flsimulate /FLSimulateVariantsDoc-2.1.pdf

**Comment by drbenmorgan** [comment]
@cherylepatrick, was this fixed with the work done for the Annecy tutorial?

**Comment by lemiere** [comment]
Start with : NemoDocDB-doc-5181-v1

**Comment by lemiere** [comment]
Someone used the DocDb to start documentation ? @cherylepatrick , @drbenmorgan
