### ISSUE TITLE
Flsimulate-configure not working (Falaise 3)

### ISSUE THREAD

**Issue by noeroy** [SuperNEMO-DBD/Falaise#6]
Hello, 
When I use flsimulate-configure program I get this result : 

![error](https://cloud.githubusercontent.com/assets/28730995/26107999/10cd9e22-3a43-11e7-8667-3be0d3f0e2f0.png)

Here are the errors I get running flsimulate-configure
[noeroy@pc179 SensitivityModule-build]$ /unix/nemo2/users/cpatrick/CadfaelBrew/bin/flsimulate-configure 
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/qt5-base/5.8.0/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau

**Comment by drbenmorgan** [comment]
This may be due to a missing `-fontconfig` option to the `qt5-base` formulae. Could you just confirm the output of `brew doctor` and `brew config` please?

**Comment by cherylepatrick** [comment]
For background, Noe's using my install on the SL6 machine, which I reinstalled from scratch yesterday/over the weekend. Here are the `brew doctor` and `brew config` outputs:
[cpatrick@pc133 testfalaise3]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/log_event.h
  /usr/local/include/trq_auth_daemon.h
  /usr/local/include/pbs_log.h
  /usr/local/include/u_lock_ctl.h
  /usr/local/include/setup_env.h
  /usr/local/include/chk_file_sec.h
  /usr/local/include/lib_net.h
  /usr/local/include/pbsnodes.h
  /usr/local/include/common_cmds.h
  /usr/local/include/attr_node_func.h
  /usr/local/include/lib_ifl.h
  /usr/local/include/lib_utils.h
  /usr/local/include/qsub_functions.h

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /unix/nemo2/users/cpatrick/CadfaelBrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/unix/nemo2/users/cpatrick/CadfaelBrew/sbin:$PATH"' >> ~/.bash_profile

[cpatrick@pc133 testfalaise3]$ brew config
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 161e0bcdf81098f678ff177e66f813f464d3f830
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 25de6aef3695fba0495bebe3d3f31d17dcad06eb
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /unix/nemo2/users/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /unix/nemo2/users/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit 0xf43
Homebrew Ruby: 2.0.0-p648 => /unix/nemo2/users/cpatrick/CadfaelBrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.13.0 => /unix/nemo2/users/cpatrick/CadfaelBrew/bin/git
Perl: /usr/bin/perl
Python: /unix/nemo2/users/cpatrick/CadfaelBrew/bin/python => /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /unix/nemo2/users/cpatrick/CadfaelBrew/bin/ruby => /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.7.0_141
Kernel: Linux 2.6.32-696.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.9 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A

**Comment by drbenmorgan** [comment]
Thanks! Could you also run the following and post the output please?

```console
$ rpm -qa | grep fontconfig
```

I still suspect fontconfig, but just need to make sure the rpms are there (they *should* be as other required dependencies would pull them in). I'll need to create a VM to reproduce and test, so may not have a fix until later tomorrow.

**Comment by cherylepatrick** [comment]
Sorry, I know it's a hassle getting it to work on different platforms. Let us know if there's anything else we can do.
```
[cpatrick@pc133 testfalaise3]$ rpm -qa | grep fontconfig
fontconfig-2.8.0-5.el6.i686
fontconfig-devel-2.8.0-5.el6.x86_64
fontconfig-2.8.0-5.el6.x86_64
```

**Comment by drbenmorgan** [comment]
This should now be fixed, and all that should be needed (famous last words...) is to do:

```console
$ brew update
$ brew upgrade qt5-base
```

This will reinstall a revision-bumped Qt5, and assuming this installs o.k., running `flsimulate-configure` should show text in the GUI now. If that's o.k. you can do

```console
$ brew cleanup qt5-base
```

to remove the old version.

**Comment by cherylepatrick** [comment]
@drbenmorgan Sorry to be the bearer of bad news as usual, but qt5-base wouldn't install and the failure point was (surprise) font-config:
```
==> Installing supernemo-dbd/cadfael/qt5-base dependency: fontconfig
==> Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/3790bcd/fo
######################################################################## 100.0%
==> Patching
==> Applying patch-2.12.1-fccache.diff
patching file src/fccache.c
==> ./configure --disable-silent-rules --enable-static --with-add-fonts=/System/Libra
==> make install RUN_FC_CACHE_TEST=false
Last 15 lines from /home/cpatrick/.cache/Homebrew/Logs/fontconfig/02.make:
Working on: /tmp/fontconfig-20170518-5565-1pi103b/fontconfig-2.12.1/doc/fontconfig-user.sgml
rm -f fontconfig-devel.txt; \
	docbook2txt fontconfig-devel.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1-1.0-51.el6.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig-20170518-5565-1pi103b/fontconfig-2.12.1/doc/fontconfig-devel.sgml
rm -f fontconfig-user.pdf; \
	docbook2pdf fontconfig-user.sgml
/bin/sh: line 1: docbook2pdf: command not found
make[2]: *** [fontconfig-user.pdf] Error 127
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/tmp/fontconfig-20170518-5565-1pi103b/fontconfig-2.12.1/doc'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/tmp/fontconfig-20170518-5565-1pi103b/fontconfig-2.12.1/doc'
make: *** [install-recursive] Error 1

READ THIS: https://github.com/SuperNEMO-DBD/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
fontconfig: include downloadable fonts as of sierra https://github.com/Homebrew/homebrew-core/pull/13550

```

**Comment by drbenmorgan** [comment]
@cherylepatrick At least it's a known issue - try the fixe from [here](https://github.com/Linuxbrew/homebrew-core/issues/1177) which is to run

```console
$ brew install fontconfig --without-docs
```

then try reinstalling qt5. Not quite sure why it failed on your machine, as I tested it on a CentOS 6.9 with `cadfael-bootstrap` run. Anyway, try the above first.

**Comment by cherylepatrick** [comment]
It worked! Thanks @drbenmorgan ! Don't know why it didn't work before but these machines are always a bit strange.

**Comment by cherylepatrick** [comment]
By the way: there are some errors coming up in the console, but as far as I can tell they aren't causing actual problems: 
libGL error: unable to load driver nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau

**Comment by noeroy** [comment]
Thank you very much!

**Comment by drbenmorgan** [comment]
@cherylepatrick I've seen a similar message, but with the "swrast" driver - it seems to be harmless.

This looks to be resolved, so I'll mark as closed.
