### ISSUE TITLE
Implement validation system for simulation, reconstruction

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/Falaise#61]
In preparation for data, a system for validating the simulation and reconstruction implementations is needed. With the current model for data flow, this should probably be split into 

* Validation of raw simulation output, before signal/digitization
  - ~~Check that correct Geant4 physics processes/lists are used~~ Store this information in metadata, basically Geant4 version and the name of the packaged Physics List.
  - ~~Checks of event generators~~ Mostly validating `genbb` physics
  - Checks of geometry: also can be handled by metadata (which geometry used), checks handed off to geometry responsibles/tests.
* ~~Validation of signal/digitization~~
  - ~~Awaits development of these, best dealt with in ASB/Digitization modules?~~
* Validation of calibration/reconstruction
  - Checks on modules, parameters of modules etc?

The above is intentionally split into stages so any issues are flagged close to where they occur, and also because each is validating different areas.

Each stage should produce a, to be defined, set of plots/quantities to be stored for comparison with later changes (e.g. update Geant4 version in simulation). A set of standard sources/tests should be defined (e.g. 2nBB), plus needed statistics for good comparison.

I think we start with the current production version of Falaise (3.1.1 at time of writing) to form the baseline for comparison.

EDIT: Clarified check on Geant4 and version to take baseline from.

**Comment by drbenmorgan** [comment]
Note - I have assigned relevant coordinators to the issue, but they should also find volunteers for the tasks (see the labels)!

**Comment by cherylepatrick** [comment]
Assigning myself 'cos I am working on this.

**Comment by drbenmorgan** [comment]
Just updating following discussion with @yramachers. He has a new simulation validation module in progress, which will address the core Geant4 physics (number of hits/steps etc). I've removed some items as these can be better handled by #157 or independent validation such as physics from `genbb`.

**Comment by drbenmorgan** [comment]
See of course the extras from @cherylepatrick and @yramachers:

https://github.com/SuperNEMO-DBD/ReconstructionValidationModule
https://github.com/SuperNEMO-DBD/SuperNEMOValidationTool

https://github.com/SuperNEMO-DBD/SimulationValidationModule
https://github.com/SuperNEMO-DBD/SimulationValidationTool

As these address this issue, I'll close it. Any further discussion should happen on the trackers on those repos, feeding back to Falaise any core needs/requirements from the data model/metadata!
