### ISSUE TITLE
Bad clang format

### ISSUE THREAD

**Issue by xgarrido** [SuperNEMO-DBD/Falaise#64]
As far as I can see, there are two issues with clang formatting and `rootcint`:

1. The [linkdef](https://github.com/SuperNEMO-DBD/Falaise/blob/develop/modules/EventBrowser/source/inc/falaise/snemo/view/event_browser_linkdef.h#L11) file now exhibits additionnal space arround the `+` character
2. Files that use the `ClassImp` macro (used for callback in `EventBrowser`) have broken indent (see [`status_bar.cc`](https://github.com/SuperNEMO-DBD/Falaise/blob/develop/modules/EventBrowser/source/status_bar.cc#L42) file)

**Comment by drbenmorgan** [comment]
Are there any error messages output by the compiler? I'll look at working around these with regexs/excludes, but useful to have any info that might help test.

**Comment by xgarrido** [comment]
Actually there are no warnings nor errors raised by the `g++` compiler and everything works (apparently) fine. So I think the first issue regarding the `linkdef` file can be just skipped. The second one mess up the code source indent so fixing it will be good.
