### ISSUE TITLE
Geometry - Plumb bob at top of pipe

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#68]
We need to simulate a calibration source in the put-away position, with the plumb bob raised and hopefully blocking the gammas from the source. Can we make this alternative geometry/point source of gammas?

**Comment by lemiere** [comment]
scheme is missing in the DocDB entry : http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=4327

**Comment by lemiere** [comment]
That could help but lenght is missing : http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0045/004507/001/Updates%20on%20the%20Calibration%20Source%20Deployment%20System.pdf

**Comment by cherylepatrick** [comment]
> scheme is missing in the DocDB entry : http://nile.hep.utexas.edu/cgi-bin/DocDB/ut-nemo/private/ShowDocument?docid=4327

Yeah, I looked at that one but couldn't find it

**Comment by cherylepatrick** [comment]
> That could help but lenght is missing : http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0045/004507/001/Updates%20on%20the%20Calibration%20Source%20Deployment%20System.pdf

Width is 15, don't know if the diagram on slide 8 is to scale?

**Comment by lemiere** [comment]
plumb scheme from Marek : http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0043/004327/001/5560.10_5th-gen_Geometry_2018_REV-1.pdf

**Comment by cherylepatrick** [comment]
Thanks to Marek, Ramon and Karol, we have some more info!

- [shape and dimensions of the source envelope](http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0043/004327/001/SourceEnvelopeHolder.pdf)
- [positions of the sources and plumb bob when put away](http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0043/004327/001/5000.06_DeploymentSys%2BPlumbBob%2BSources.pdf)
- [dimensions of the plumb bob](http://nile.hep.utexas.edu/DocDB/ut-nemo/docs/0043/004327/001/5560.10_5th-gen_Geometry_2018_REV-1.pdf) - material is 610 grams of Cu-110

**Comment by lemiere** [comment]
Based on updated Marek drawing : 
* on the horizontal source frame there is 6 holes on the top beam and 6 holes on the bottom beam 
for the calibration path (real source frame mass < simulated source frame mass by ~100 g)
* On running operation mode the plumb bob is far away from the demonstrator
* On calibration operation mode, the plumb bob fill the bottom holes and add 610g per plumb

Why should we implement this geometry : 
* reduce the gamma interaction cross section  
* in case of contaminated plumb bob, provide a vertex generator on the plumb bob geometry

My feeling : 
* no significant impact on the gamma interaction probability
* If we have to simulate a contaminated plumb bob, it will be coherent to study it in standard running mode, the plumb bob will be in top parking mode. We can use a single point vertex instead a real plumb bob bulk distribution. In term of solid angle, it's coherent.

So I propose to close that issue with no extra feature;
