### ISSUE TITLE
Processing/Clustering delayed hits disabled in standard reconstruction pipeline

### ISSUE THREAD

**Issue by lecdawson** [SuperNEMO-DBD/Falaise#70]
`@falaise:config/snemo/demonstrator/reconstruction/pipeline/1.0.0/flreconstruct.conf`, processing of delayed hits is disabled. Work around was to add:
TPC.processing_delayed_hits : boolean = true
to my rec.conf.
Cluster fitting to delayed tracks is also not included in the standard reconstruction pipeline. Added:
line.guess.fit_delayed_clusters : boolean = true
to my rec.conf.

**Comment by drbenmorgan** [comment]
Reconstruction task, so assigning to C&R WG

**Comment by drbenmorgan** [comment]
Fixed in the current "official" pipeline.
