### ISSUE TITLE
Energy restriction on simulated interactions

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#73]
Similar to, but I think not the same as, issue #29

In the past (Falaise 2), @fmauger  helped me to generate 2nubb events with a lower energy cut-off. (Basically, I was using them for a sensitivity study in which I knew I would make an energy cut, so there was little point in wasting disk space by generating a load of events that were likely to immediately get removed).

Important point in this case is that you need to be able to know what fraction of events from the full distribution falls into the cut range (so that you can calculate efficiencies based on the full distribution, including the low-energy events that never got simulated). I hope that makes sense...

Is there a way to do this with the new Falaise 3 flsimulate-configure interface?

Here are the instructions @fmauger gave me for Falaise 2, which worked fine but involved some amount of hacking config files:

In Falaise, DBD generators of interest are defined in the
`<falaises_source_dir>/resources/config/common/simulation/primary_events/1.1/generators/dbd.def` 
file.

Example: the one you have used recently is configured through the 
following block:
<pre>
##########################################################################
[name="Se82.2nubb" type="genbb::wdecay0"]
#@config Two neutrino double beta decay of Se-82, 2nubb [DBD]
decay_type      : string  = "DBD"
decay_isotope   : string  = "Se82"
decay_dbd_level : integer = 0
decay_dbd_mode  : integer = 4 # 2nubb
</pre>

You can add a new generator like this:
<pre>
##########################################################################
[name="Se82.2nubb.HE" type="genbb::wdecay0"]
#@config Two neutrino double beta decay of Se-82, 2nubb [DBD] 
(Hhgh-energy part)
decay_type      : string = "DBD"
decay_isotope   : string = "Se82"
decay_dbd_level : integer = 0
decay_dbd_mode  : integer = 4 # 2nubb
energy_min      : real as energy = 2.2 MeV
energy_max      : real as energy = 3.5 MeV
</pre>

The documentation of the wdecay0 generator is at:
`<bayeux_install_dir>/share/Bayeux-{bayeux_version}/Documentation/API/html/__ocd__genbb__wdecay0.html`

This generator will sample only DBD events with Esum in the [2.2-3.5]  MeV range and thus will save a huge amount of CPU and storage. AFAIR, the statistical weight of the primary event can be obtained from the `double genbb::primary_event::get_genbb_weight() const` method called from the primary event stored in the stored `mctools::simulated_data` (see `const primary_event_type& 
mctools::simulated_data::get_primary_event() const`.

This number gives you the ratio between the number of events effectively 
generated and the number of events which should have been generated in the whole 
energy spectrum.I think the easiest way to fetch it is to run flsimulate with only one event and use and .xml output file. You then just have to grep the `genbb_weight` string to find the weight value.

**Comment by drbenmorgan** [comment]
Fixed by #75
