### ISSUE TITLE
Bug in description of tags for the Falaise urn_db_service  

### ISSUE THREAD

**Issue by fmauger** [SuperNEMO-DBD/Falaise#79]
Directory "resources/urn/db" contains a set of files that describe the dependencies between various
setup published in Falaise for simulation/reconstruction processing.
A graph analysis performed on the current description revealed some cycles in the relationships between some urn nodes related to the management and accounting of variant profiles. 
This must be fixed. The current model to manage variant profile through their URN identifier is broken.
Work to do:
- fix some of the "xxx_infos.defs" files to remove some invalid links (backward edges)
- set a valid scheme to describe correctly the dependencies between setups, variant services and variant profiles and refactor the broken links as forward edges/links
- modify the flsimulate(-configure) code to take into account these changes while searching default urn associated to a variant profile
- update the README file to describe the new rules.

A fix already exists as one of my a feature branches. Will PR it ASAP.
To be assigned to fmauger.

**Comment by drbenmorgan** [comment]
@fmauger thanks for the report, and we'll await the PR.

I would also add to the todo list additional documentation on the URN model/implementation plus instructions for developers on managing it. This is strongly coupled to #33, #57, and we need to also ensure that #15 isn't repeated. Please review those as part of the PR!
