### ISSUE TITLE
failed to grab CD bank

### ISSUE THREAD

**Issue by HanFangXie** [SuperNEMO-DBD/Falaise#83]
I am running flreconstruct -i Bi214_anode_wire_bulk.brio -p ../SensitivityModule/SensitivityModule.conf 
and see this error:

Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180113-82641-1nv6yqc/Bayeux-Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180113-82641-1nv6yqc/Bayeux-Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
[notice:void datatools::library_loader::init():450] Automatic loading of library 'SensitivityModule'...
failed to grab CD bank : [const T &datatools::things::get(const std::string &) const [T = snemo::datamodel::calibrated_data]:103: No object named 'CD' !]
failed to grab CD bank : [const T &datatools::things::get(const std::string &) const [T = snemo::datamodel::calibrated_data]:103: No object named 'CD' !]

I am working on a mac os high sierra 10.13.2, root 6.12.04.

**Comment by drbenmorgan** [comment]
@cherylepatrick, looks like a SensitivityModule issue?

**Comment by cherylepatrick** [comment]
@HanFangXie is there any chance you are running this on a simulated file rather than one that has been fully reconstructed with the basic flreconstruct pipeline? That's the error I'd expect to see in that case.

As an aside, are you sure you should be looking at anode wires? I think you want field wires. We will talk about this later today.

**Comment by HanFangXie** [comment]
Hi All, 
Sorry about that. Yes, I used the wrong brio file which is only a simulated one. I should used the fully reconstructed one. 
And, I agree with Cheryl. Field wires would make more sense coz radon decay products are normally positive.
