### ISSUE TITLE
flvisualize (G)UI: Event counter in the menu bar overflows while browsing event in sequential reading mode (xml)

### ISSUE THREAD

**Issue by fmauger** [SuperNEMO-DBD/Falaise#89]
Browsing an XML output file by flsimulate with flvisualize, when we reach the last event in the sequence, it is still possible to click on the [>] "next event" button. The event counter in the left bottom corner is then incremented and the displayed event is frozen to the last one in the sequence. This is strange and confusing.
One would expect the end of the stream could be detected and that the  "next event" button is inhibited.

**Comment by drbenmorgan** [comment]
Closing due to zero manpower and higher priority tasks
