### ISSUE TITLE
Falaise's system library does not lock its URN Db Service before registration

### ISSUE THREAD

**Issue by fmauger** [SuperNEMO-DBD/Falaise#91]
Falaise publishes a set of official URNs, corresponding to specific experimental/simulation/reconstruction setups with associated configuration & data files, through a dedicated _system_ URN Database Service.
The service is instantiated as a singleton of the `falaise::detail::falaise_sys` class.
When loaded, the URN Database Service registers itself to the Bayeux datatools' kernel, making itself visible to and usable by other components/libraries.
A client URN Database Service object (the depender) has the hability to mount the Falaise's system URN Database Service object (the dependee/provider) and  then use some URNs registered in this database. However, this operation is only allowed if the dependee service is **locked**, which means it is not possible to remove or add more URNs in it, to suppress  the risk to break dependencies for the depender client service which subscribed to the dependee service.
The current implementation lacks the explicit lock/unlock calls that would enable the mounting
of the Falaise's system URN Database Service by external components. This is considered as a bug.
The proposed solution is the same that was implemented to solve https://github.com/BxCppDev/Bayeux/issues/16.

**Comment by drbenmorgan** [comment]
For future PRs, it would be cleaner to just submit the PR with the above information in. Also, please provide a minimal example exercising/demonstrating the bug.
