### ISSUE TITLE
MCC2.1 request : Event generator and new geometry -- Sn124

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/Falaise#98]
Hi,

After Coll. meeting discussions, is that possible to propose new generator for  Sn124 BB source ? @fmauger 
The geometry is to define (source dimension/position) -- @emchauve 
 Sn124 isotope is avaible in decay0

Thx
Yves

**Comment by drbenmorgan** [comment]
Fixed in #104 104
